package prg.business.group;

import java.io.Serializable;
import java.util.ListResourceBundle;

public class PbEditGroupResourceBundle extends ListResourceBundle implements Serializable {

    protected Object[][] getContents() {
        return contents;
    }
    static final Object contents[][] = {
        {"deleteArGraphMaster", "delete from prg_ar_graph_master where report_id=&"}, {"deleteArPersonRep", "delete from prg_ar_personalized_reports where prg_report_id=&"}, {"deleteArQueryDet", "delete from prg_ar_query_detail where report_id=&"}, {"deleteArParDetails", "delete from prg_ar_report_param_details where report_id=&"}, {"deleteRepTimeDetail", "delete from prg_ar_report_time_detail where rep_time_id in(select rep_time_id from prg_ar_report_time where report_id=&)"}, {"deleteRepTimeMaster", "delete from prg_ar_report_time where report_id=&"}, {"deleteReportViewDetails", "delete from prg_ar_report_view_by_details where view_by_id in(select view_by_id from prg_ar_report_view_by_master where report_id=&)"}, {"deleteRepViewMaster", "delete from prg_ar_report_view_by_details where view_by_id in(select view_by_id from prg_ar_report_view_by_master where report_id=&)"}, {"deleteUserReports", "delete from prg_ar_user_reports where report_id=&"}, {"deleteRepDetails", "delete from prg_ar_report_details where report_id=&"}, {"deleteReportMaster", "delete from prg_ar_report_master where report_id=&"} // added by praveen to insert data for time based formula
        , {"insrtingbussrcdtails", "insert into prg_grp_buss_table_src_details(BUSS_SRC_TABLE_DTL_ID,BUSS_SRC_ID,BUSS_TABLE_ID,COLUMN_ALIAS,COLUMN_TYPE)"
            + " values(PRG_GRP_BUSS_TAB_SRC_DTLS_SEQ.nextval,(select distinct buss_source_id from prg_grp_buss_table_src where buss_table_id = '&'),'&','&','TIMECALUCULATED')"}, {"getdisplayname", "select COLUMN_DISP_NAME from prg_grp_buss_table_details where buss_column_id = '&'"}, {"insrtingprgbstbldtls", "insert into prg_grp_buss_table_details(BUSS_COLUMN_ID,BUSS_TABLE_ID,COLUMN_NAME,BUSS_SRC_TABLE_DTL_ID,COLUMN_TYPE,ACTUAL_COL_FORMULA,DEFAULT_AGGREGATION,COLUMN_DISP_NAME,COLUMN_DISPLAY_DESC,REFFERED_ELEMENTS,BASE_COLUMN_ID)"
            + " values(PRG_GRP_BUSS_TABLE_DETAILS_seq.nextval,'&','&',PRG_GRP_BUSS_TAB_SRC_DTLS_SEQ.CURRVAL,'TIMECALUCULATED','&','&','B_' || CAST((PRG_GRP_BUSS_TABLE_DETAILS_seq.CURRVAL) AS VARCHAR(256)),'&','&','&')"},
        //added by ramesh janakuttu to select tableid,columnid
        {"gettableid", "select BD.*,BT.* from PRG_GRP_BUSS_TABLE_DETAILS BD ,PRG_GRP_BUSS_TABLE BT  where BD.BUSS_COLUMN_ID='&' AND BT.BUSS_TABLE_ID=BD.BUSS_TABLE_ID"},
        {"getSeq", "select PRG_GRP_BUSS_TABLE_DETAILS_seq.nextval from dual"},
        {"getcolumndisplaydes", "select BD.*,BT.* from PRG_GRP_BUSS_TABLE_DETAILS BD ,PRG_GRP_BUSS_TABLE BT  where BD.BUSS_COLUMN_ID='&' AND BT.BUSS_TABLE_ID=BD.BUSS_TABLE_ID"},
        {"getDetails", "SELECT A.BUSS_COLUMN_ID,MAX(A.default_aggregation) default_aggregation ,MAX(AVG_col_formula) AVG_col_formula,MAX(MIN_col_formula) MIN_col_formula ,MAX(MAX_col_formula) MAX_col_formula ,MAX(SUM_col_formula) SUM_col_formula,MAX(SUM_col_formula) CNT_col_formula,MAX(SUM_col_formula) CNTD_col_formula,c.buss_table_name,c.db_table_id,db_column_id,column_name,column_disp_name,column_type,column_display_desc,role_flag FROM(SELECT (CASE WHEN base_column_id *1 IS NULL THEN BUSS_COLUMN_ID ELSE base_column_id *1 END) BUSS_COLUMN_ID,(CASE WHEN base_column_id *1 IS NULL THEN default_aggregation ELSE NULL END) default_aggregation,(CASE WHEN base_column_id *1 IS NOT NULL AND upper(default_aggregation)='AVG' THEN 'Y' ELSE NULL END) AVG_col_formula ,( CASE WHEN base_column_id *1 IS NOT NULL AND upper(default_aggregation)='MIN' THEN 'Y' ELSE NULL END) MIN_col_formula ,(CASE WHEN base_column_id *1 IS NOT NULL AND upper(default_aggregation)='MAX' THEN 'Y' ELSE NULL END) MAX_col_formula ,(CASE WHEN base_column_id *1 IS NOT NULL AND upper(default_aggregation)='SUM' THEN 'Y' ELSE NULL END) SUM_col_formula ,(CASE WHEN base_column_id *1 IS NOT NULL AND upper(default_aggregation)='COUNT' THEN 'Y' ELSE NULL END) CNT_col_formula ,(CASE WHEN base_column_id *1 IS NOT NULL AND upper(default_aggregation)='COUNTDISTINCT' THEN 'Y' ELSE NULL END) CNTD_col_formula FROM prg_grp_buss_table_details) A,prg_grp_buss_table_details B,prg_grp_buss_table c WHERE A.BUSS_COLUMN_ID= B.BUSS_COLUMN_ID and B.buss_table_id = C.buss_table_id AND B.buss_table_id = '&' AND column_type NOT IN('TIMECALCULATED','TIMECALUCULATED','TIMESUMMARISED','TIMESUMMARIZED')GROUP BY A.BUSS_COLUMN_ID,c.buss_table_name,c.db_table_id,db_column_id,column_name,column_disp_name,column_type,column_display_desc,role_flag ORDER BY column_disp_name DESC"}
    };
}
