/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.progen.connection;

import java.io.Serializable;
import java.util.ListResourceBundle;

/**
 *
 * @author Administrator
 */
public class ConnectionResourceBundle extends ListResourceBundle implements Serializable {

    @Override
    protected Object[][] getContents() {
        return contents;
    }
    static final Object contents[][] = {
        {"upDateUserConn", "update PRG_USER_CONNECTIONS set CONNECTION_NAME ='&', USER_NAME='&', PASSWORD='&', SERVER='&', SERVICE_ID='&',SERVICE_NAME='&',"
            + " PORT='&',  DSN_NAME='&', DB_CONNECTION_TYPE='&',DBNAME='&' where connection_id='&'"}, {"checkTableName", "select table_name from prg_db_master_table where connection_id=&"}, {"saveQueryTable", "Insert into  prg_db_master_table(CONNECTION_ID,USER_SCHEMA,TABLE_ID,TABLE_NAME,TABLE_ALIAS,TABLE_TYPE,CREATED_BY,UPDATED_BY,CREATED_ON,UPDATED_ON,DB_QUERY) values ('&','&',PRG_DATABASE_MASTER_SEQ.nextval,'&','&','&','&','&','&','&','&')"}, {"getConnectionId", "SELECT PUC.USER_NAME, PUC.PASSWORD, PUC.SERVER, PUC.SERVICE_ID, PUC.SERVICE_NAME, PUC.PORT,PUC.DSN_NAME, PUC.DB_CONNECTION_TYPE FROM PRG_USER_CONNECTIONS PUC where PUC.connection_id=&"}, {"saveQueryDetailsTable", "Insert into  PRG_DB_MASTER_TABLE_DETAILS(column_id, table_id, table_col_name, table_col_cust_name, col_type, col_length, is_primary_key, is_active) values (PRG_DB_MASTER_TABLE_DTLS_SEQ.nextval,PRG_DATABASE_MASTER_SEQ.currval,'&','&','&',&,'N','Y') "} //added by susheela
        , {"checkUserConnection", "select * from prg_grp_master where connection_id=&"}, {"deleteUserConnection", "delete from prg_user_connections where connection_id=&"}, {"deleteDbTables", "delete from prg_db_master_table where connection_id="}, {"deleteDbTablesDetails", "delete from prg_db_master_table_details where table_id in(select distinct table_id from prg_db_master_table where connection_id=&)"}, {"deleteDbRelDetails", "delete from prg_db_table_rlt_details where relationship_id in(select relationship_id from "
            + " prg_db_table_rlt_master where table_id in(select distinct table_id from prg_db_master_table where connection_id=&))"}, {"deleteDbRelDetails2", "delete from prg_db_table_rlt_details where relationship_id in(select relationship_id from prg_db_table_rlt_master where "
            + " table_id2 in(select distinct table_id from prg_db_master_table where connection_id=&))"}, {"deleteDbRelMaster1", "delete from prg_db_table_rlt_master where relationship_id in(select relationship_id from prg_db_table_rlt_master where table_id in(select distinct table_id from prg_db_master_table where connection_id=&))"}, {"deleteDbRelMaster2", "delete from prg_db_table_rlt_master where relationship_id in(select relationship_id from prg_db_table_rlt_master where table_id2 in(select distinct table_id from prg_db_master_table where connection_id=&))"}, {"getRelatedDbTables", "select * from prg_db_table_rlt_master where table_id='&' union select * from prg_db_table_rlt_master where table_id2='&'"}, {"getGroupNames", "select * from prg_grp_master"}, {"getRelatedGroups", "select * from prg_grp_buss_table_master_view where db_table_id in(select s_table_id from prg_db_table_rlt_details where p_table_id='&' union select p_table_id from prg_db_table_rlt_details where s_table_id='&')"}, {"getDbCols", "select * from prg_db_master_table_details where column_id in( select p_col_id1 from prg_db_table_rlt_details where s_table_id='&' union select s_col_id1 from prg_db_table_rlt_details where p_table_id='&' )"}, {"relTabInfo", "select * from prg_db_master_table where table_id in(select s_table_id from prg_db_table_rlt_details where p_table_id='&' union select p_table_id from prg_db_table_rlt_details where s_table_id='&')"}, {"dbTableDetales", "select * from prg_db_master_table where table_id=&"}, {"getRelatedInfo", "SELECT db.relationship_id,buss_relation_id,mst.table_name,db.table_id2 table_id, db.table_id table_id2, db.actual_clause, CASE   WHEN grp.buss_relation_id IS NULL "
            + "THEN 'N'   ELSE 'Y' END grp_buss_relationship, CASE   WHEN db.ACTUAL_CLAUSE = grp.actual_clause   THEN 'Y'   ELSE 'N' END Are_equal FROM prg_db_table_rlt_master db "
            + "inner join PRG_DB_MASTER_TABLE mst on (db.table_id2 = mst.table_id) LEFT JOIN (SELECT a.buss_relation_id,c.db_table_name,   b.db_table_id,   a.buss_table_id, "
            + "a.buss_table_id2,   c.db_table_id db_table_id2,   a.actual_clause FROM prg_grp_buss_table_rlt_master a,   prg_grp_buss_table_master_view b, "
            + " prg_grp_buss_table_master_view c WHERE a.buss_table_id=b.buss_table_id AND a.buss_table_id2 =c.buss_table_id AND b.grp_id         ='&' "
            + "AND c.grp_id         ='&' AND b.db_table_id    = '&' ) grp ON(db.table_id    =grp.db_table_id AND db.table_id2  =grp.db_table_id2) "
            + "WHERE db.table_id = '&'UNION ALL SELECT db.relationship_id, buss_relation_id,mst.table_name, db.table_id, db.table_id2, db.actual_clause, "
            + "CASE   WHEN grp.buss_relation_id IS NULL   THEN 'N'   ELSE 'Y' END grp_buss_relationship, CASE   WHEN db.ACTUAL_CLAUSE = grp.actual_clause "
            + " THEN 'Y'   ELSE 'N' END Are_equal FROM prg_db_table_rlt_master db inner join PRG_DB_MASTER_TABLE mst on (db.table_id = mst.table_id) LEFT JOIN "
            + "(SELECT a.buss_relation_id,b.db_table_name,   b.db_table_id,   a.buss_table_id,   a.buss_table_id2,   c.db_table_id db_table_id2,   a.actual_clause "
            + "FROM prg_grp_buss_table_rlt_master a,   prg_grp_buss_table_master_view b,   prg_grp_buss_table_master_view c WHERE a.buss_table_id=b.buss_table_id "
            + "AND a.buss_table_id2 =c.buss_table_id AND b.grp_id ='&' AND c.grp_id ='&' AND c.db_table_id = '&' ) grp ON(db.table_id =grp.db_table_id AND db.table_id2   =grp.db_table_id2) WHERE db.table_id2 = '&'"}, {"updatebussTable", "update  prg_grp_buss_table_rlt_master set ACTUAL_CLAUSE='&'  where BUSS_RELATION_ID='&'"}, {"insertbussTableForOracle", "INSERT INTO PRG_GRP_BUSS_TABLE_RLT_MASTER  ( BUSS_RELATION_ID,BUSS_TABLE_ID,BUSS_TABLE_ID2,REALTIONSHIP_TYPE,ACTUAL_CLAUSE,ACTUAL_CLAUSE1,CLAUSE_TYPE ) "
            + "select PRG_GRP_BUSS_TAB_RLT_MSTR_SEQ.NEXTVAL BUSS_RELATION_ID, B.BUSS_TABLE_ID table_id,C.BUSS_TABLE_ID table_id2, DB.REALTIONSHIP_TYPE, db.actual_clause, "
            + " DB.ACTUAL_CLAUSE1, db.clause_type from prg_db_table_rlt_master db, prg_grp_buss_table_master_view B, prg_grp_buss_table_master_view C where B.DB_TABLE_ID = db.table_id and c.DB_TABLE_ID = db.table_id2 AND B.GRP_ID ='&' AND C.GRP_ID='&' AND DB.RELATIONSHIP_ID = '&'"}, {"insertbussTableForSql", "INSERT INTO PRG_GRP_BUSS_TABLE_RLT_MASTER  ( BUSS_TABLE_ID,BUSS_TABLE_ID2,REALTIONSHIP_TYPE,ACTUAL_CLAUSE,ACTUAL_CLAUSE1,CLAUSE_TYPE ) "
            + "select  B.BUSS_TABLE_ID table_id,C.BUSS_TABLE_ID table_id2, DB.REALTIONSHIP_TYPE, db.actual_clause, "
            + " DB.ACTUAL_CLAUSE1, db.clause_type from prg_db_table_rlt_master db, prg_grp_buss_table_master_view B, prg_grp_buss_table_master_view C where B.DB_TABLE_ID = db.table_id and c.DB_TABLE_ID = db.table_id2 AND B.GRP_ID ='&' AND C.GRP_ID='&' AND DB.RELATIONSHIP_ID = '&'"}, {"deleteDbTableRelDetails", " delete from prg_db_table_rlt_details where relationship_id=&"}, {"getRelatedDbTabForEdit1", "select * from prg_db_table_rlt_details where p_table_id=&  or s_table_id=&"}, {"getRelatedDbTabForEdit2", "select * from prg_db_table_rlt_details where s_table_id=&  and p_table_id=&"}, {"deleteDbRelMaster", "delete from prg_db_table_rlt_master where relationship_id=&"}, {"getConnectionIdByElementId", "select DISTINCT a.USER_NAME,  a.PASSWORD,  a.SERVER,  a.SERVICE_ID,  a.SERVICE_NAME,  a.PORT, a.DSN_NAME, a.DB_CONNECTION_TYPE,a.dbname, a.connection_id,a.max_active, a.max_wait  "
            + "from PRG_USER_CONNECTIONS a,PRG_USER_ALL_INFO_DETAILS b  where a.connection_id=b.connection_id and b.element_id='&'"}, {"getConnectionByTable", "SELECT  PUC.USER_NAME, PUC.PASSWORD, PUC.SERVER, PUC.SERVICE_ID, PUC.SERVICE_NAME, PUC.PORT,PUC.DSN_NAME, PUC.DB_CONNECTION_TYPE,PUC.DBNAME,puc.connection_id,puc.max_active,puc.max_wait  FROM PRG_USER_CONNECTIONS PUC,prg_db_master_table PDMT WHERE PDMT.connection_id=PUC.connection_id AND pdmt.table_id=&"}, {"getConnectionByConId", "select user_name,password,server,service_id,service_name,port,dsn_name,db_connection_type,dbname,connection_id,max_active,max_wait FROM PRG_USER_CONNECTIONS where connection_id=&"}, {"getConnectionByGroupId", "select CONNECTION_ID from PRG_GRP_MASTER where GRP_ID=&"}, {"getColumnnameFromCustDB", "Select COLUMN_NAME,DATA_TYPE,DATA_LENGTH  from user_tab_columns where table_name='&'"}, {"getColumnnameFromOrgDB", "select TABLE_COL_NAME from prg_db_master_table_details where table_id = &"}, {"insertColumnToDbTable", "insert into prg_db_master_table_details values (PRG_DB_MASTER_TABLE_DTLS_SEQ.nextval,&,'&','&','&',&,'&','&')"}, {"insertColumnToDbTableforSQL", "insert into prg_db_master_table_details(TABLE_ID,TABLE_COL_NAME,TABLE_COL_CUST_NAME,COL_TYPE,COL_LENGTH,IS_PRIMARY_KEY,IS_ACTIVE) values (&,'&','&','&',&,'&','&')"}, {"checkInBussGrp", "select * from prg_grp_buss_table where db_table_id = &"}, {"checkInBussSrc", "select * from prg_grp_buss_table_src where buss_table_id = &"}, {"getColumnDetails", "select * from prg_db_master_table_details where table_id = & and table_col_name in( &)"}, {"insertBussGrpSrc", "insert into prg_grp_buss_table_src_details  values (PRG_GRP_BUSS_TAB_SRC_DTLS_SEQ.NEXTVAL,'&','&','&','&','&','&')"}, {"insertBussGrpSrcforSQL", "insert into prg_grp_buss_table_src_details(BUSS_SRC_ID,DB_TABLE_ID,BUSS_TABLE_ID,DB_COLUMN_ID,COLUMN_ALIAS,COLUMN_TYPE)  values ('&','&','&','&','&','&')"}, {"insertInGrpDetails", "insert into prg_grp_buss_table_details( buss_column_id,buss_src_table_dtl_id,buss_table_id,column_name,column_type,db_table_id,db_column_id,is_union,column_disp_name,column_display_desc,role_flag)"
            + "values(PRG_GRP_BUSS_TABLE_DETAILS_seq.nextval,PRG_GRP_BUSS_TAB_SRC_DTLS_SEQ.currval,'&','&','&','&','&','&','&','&','&')"}, {"insertInGrpDetailsforSQL", "insert into prg_grp_buss_table_details( buss_table_id,column_name,column_type,db_table_id,db_column_id,is_union,column_disp_name,column_display_desc,role_flag)"
            + "values('&','&','&','&','&','&','&','&','&')"}, {"insertInGrpDetailsforMYSQL", "insert into prg_grp_buss_table_details( buss_src_table_dtl_id,buss_table_id,column_name,column_type,db_table_id,db_column_id,is_union,column_disp_name,column_display_desc,role_flag)"
            + "values((select LAST_INSERT_ID(BUSS_SRC_TABLE_DTL_ID) FROM prg_grp_buss_table_src_details ORDER BY 1 DESC LIMIT 1),'&','&','&','&','&','&','&','&','&')"}, {"checkInBussRole", "select * from prg_user_sub_folder_tables where buss_table_id =& "} //    ,{"getBussGrpDetails",""}
        , {"insertInBusRole", "INSERT INTO prg_user_sub_folder_elements(element_id,sub_folder_id,buss_table_id,buss_col_id,buss_col_name,user_col_name,user_col_desc,user_col_type,"
            + "ref_element_id,ref_element_type,sub_folder_tab_id,use_report_flag)VALUES(&,'&','&','&','&','&','&','&','&','&','&','&' )"}, {"insertInBusRoleforSQL", "INSERT INTO prg_user_sub_folder_elements(sub_folder_id,buss_table_id,buss_col_id,buss_col_name,user_col_name,user_col_desc,user_col_type,"
            + "ref_element_type,sub_folder_tab_id,use_report_flag)VALUES(&,'&','&','&','&','&','&','&','&','&')"}, {"getFolderDetails", "select pf.*,pd.* from prg_user_folder pf ,prg_user_folder_detail pd where pd.sub_folder_id in (&) and pf.folder_id=pd.folder_id"}, {"queryFromAllInfo", "select * from prg_user_all_info_details  where folder_id = &"}, {"getColumnnameFromCustDB", "Select COLUMN_NAME,DATA_TYPE,DATA_LENGTH  from user_tab_columns where table_name='&'"}, {"checkinBussTable", "select * from prg_grp_buss_table where db_table_id = &"}, {"deleteDbMaster", "DELETE from PRG_DB_MASTER_TABLE WHERE TABLE_ID =&"}, {"deleteDbMasterTabDetails", "DELETE from prg_db_master_table_details where table_id=&"}, {"deleteDbTabRelation", "DELETE from prg_db_table_rlt_details WHERE RELATIONSHIP_ID IN (SELECT RELATIONSHIP_ID FROM PRG_DB_TABLE_RLT_MASTER WHERE TABLE_ID = &  )"}, {"deleteDbTabRelationDetails", "DELETE from PRG_DB_TABLE_RLT_MASTER WHERE TABLE_ID = & "}, {"checkInBussMaster", "select * from prg_grp_master where connection_id =& "}, {"deletedbMastforCon", "delete from prg_db_master_table where connection_id = &"}, {"deleteUserConnection", "delete from prg_user_connections where connection_id=& "}, {"updateBussTableDetails", "UPDATE prg_grp_buss_table_details SET column_disp_name = 'B_' || CAST((buss_column_id) AS VARCHAR(256)) WHERE BUSS_TABLE_ID  = &"}, {"updateBussTableDetails1", "UPDATE prg_grp_buss_table_details SET column_disp_name = concat('B_', CAST(buss_column_id AS CHAR)) WHERE BUSS_TABLE_ID  = &"}, {"deletedbMastDetails", "delete from  prg_db_master_table_details where table_id in (select table_id from prg_db_master_table where connection_id = &)"} //added by Nazneen
        , {"updateBussTableDetails2", "UPDATE prg_grp_buss_table_details SET column_disp_name = 'B_' + CAST((buss_column_id) AS VARCHAR(256)) WHERE BUSS_TABLE_ID  = &"}
    };
}
