/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.progen.dimensions;

import java.io.Serializable;
import java.util.ListResourceBundle;

/**
 *
 * @author Administrator
 */
public class PbDimensionResourceBundle extends ListResourceBundle implements Serializable {

    protected Object[][] getContents() {
        return contents;
    }
    static final Object contents[][] = {
        {"getDimensionDet", " SELECT t1.dimension_id,t1.dimension_name, "
            + "q.tab_id,d.table_name,q.dim_id,q.dim_tab_id,count(q.tab_id) "
            + "over (partition by t1.dimension_id) as table_count  FROM "
            + "prg_qry_dim_tables q ,  prg_db_master_table d,"
            + "PRG_QRY_DIMENSIONS t1  WHERE q.tab_id= d.table_id AND "
            + "q.dim_id=t1.dimension_id and t1.connection_id=& order by dimension_id,tab_id"}, {"getDimensiontables", " SELECT t1.dimension_id,t1.dimension_name, "
            + "q.tab_id,d.table_name,q.dim_id,q.dim_tab_id,count(q.tab_id) "
            + "over (partition by t1.dimension_id) as table_count  FROM "
            + "prg_qry_dim_tables q ,  prg_db_master_table d,"
            + "PRG_QRY_DIMENSIONS t1  WHERE q.tab_id= d.table_id AND "
            + "q.dim_id=t1.dimension_id and t1.connection_id=& and t1.dimension_id=& order by dimension_id,tab_id"}, {"getDimensionDetMysql", " SELECT t1.dimension_id,t1.dimension_name, "
            + "q.tab_id,d.table_name,q.dim_id,q.dim_tab_id,count(q.tab_id) "
            + " as table_count  FROM "
            + "prg_qry_dim_tables q ,  prg_db_master_table d,"
            + "PRG_QRY_DIMENSIONS t1  WHERE q.tab_id= d.table_id AND "
            + "q.dim_id=t1.dimension_id and t1.connection_id=& GROUP BY t1.dimension_id,  t1.dimension_name,  q.tab_id,  d.table_name,  q.dim_id,  q.dim_tab_id order by dimension_id,tab_id"}, {"getDimensiontablesMysql", " SELECT t1.dimension_id,t1.dimension_name, "
            + "q.tab_id,d.table_name,q.dim_id,q.dim_tab_id,count(q.tab_id) "
            + " as table_count  FROM "
            + "prg_qry_dim_tables q ,  prg_db_master_table d,"
            + "PRG_QRY_DIMENSIONS t1  WHERE q.tab_id= d.table_id AND "
            + "q.dim_id=t1.dimension_id and t1.connection_id=& and t1.dimension_id=& GROUP BY t1.dimension_id, t1.dimension_name, q.tab_id, d.table_name, q.dim_id, q.dim_tab_id order by dimension_id,tab_id"}, {"", ""}, {"", ""}, {"", ""}, {"", ""}, {"", ""} //added by susheela satrt
        , {"checkQryDimension", "select * from prg_grp_dimensions where qry_dim_id=&"}, {"checkDimForRename", "select dimension_id,dimension_name from prg_qry_dimensions where connection_id=&"}, {"deleteDimTabDetails", "delete from prg_qry_dim_tab_details where dim_tab_id in(select dim_tab_id from prg_qry_dim_tables where dim_id=&)"}, {"deleteDimTables", "delete from prg_qry_dim_tables where dim_id=&"}, {"deleteDimRelDetails", "delete from prg_qry_dim_rel_details where rel_id in(select rel_id from prg_qry_dim_rel where dim_id=&)"}, {"deleteDimRel", "delete from prg_qry_dim_rel where dim_id=&"}, {"deleteDimMemDetails", "delete from prg_qry_dim_member_details where mem_id in(select member_id from prg_qry_dim_member where dim_id=&)"}, {"deleteDimMember", "delete from prg_qry_dim_member WHERE dim_id=&"}, {"deleteDimension", "delete from prg_qry_dimensions where dimension_id=&"}, {"renameQryDimension", "update prg_qry_dimensions set dimension_name='&', dimension_desc='&' where dimension_id=&"}, {"renameGrpDimension", "update PRG_GRP_DIMENSIONS set DIM_NAME ='&', DIM_DESC='&' where QRY_DIM_ID=&"}, {"renameRepDimension", "update PRG_USER_SUB_FOLDER_TABLES set DIM_NAME ='&' where dim_id in (select dim_id from prg_grp_dimensions where qry_dim_id='&')"}, {"getDimName", "select dimension_name,dimension_desc from prg_qry_dimensions where dimension_id=&"} //added by susheela over
        //added by sunita
        , {"insertGrpDimTablesDetails", "INSERT INTO PRG_GRP_DIM_TAB_DETAILS(DIM_TAB_COL_ID, DIM_TAB_ID, COL_ID, IS_AVAILABLE, IS_PK_KEY) "
            + "SELECT (PRG_GRP_DIM_TAB_DETAILS_SEQ.NEXTVAL) AS DIM_TAB_COL_ID,& AS DIM_TAB_ID,btdv.buss_column_id, "
            + "dtd.is_available AS COL_ID, dtd.is_pk_key FROM PRG_GRP_BUSS_TABLE_DTLS_VIEW BTDV,PRG_QRY_DIM_TAB_DETAILS DTD "
            + "WHERE btdv.db_column_id= dtd.col_id AND dtd.dim_tab_id=& and dtd.is_available='Y' and BTDV.grp_id=& and btdv.buss_column_id not in (select COL_ID from PRG_GRP_DIM_TAB_DETAILS)"}, {"insertGrpDimTablesDetails1", "INSERT INTO PRG_GRP_DIM_TAB_DETAILS( DIM_TAB_ID, COL_ID, IS_AVAILABLE, IS_PK_KEY) "
            + "SELECT & AS DIM_TAB_ID,btdv.buss_column_id, "
            + "dtd.is_available AS COL_ID, dtd.is_pk_key FROM PRG_GRP_BUSS_TABLE_DTLS_VIEW BTDV,PRG_QRY_DIM_TAB_DETAILS DTD "
            + "WHERE btdv.db_column_id= dtd.col_id AND dtd.dim_tab_id=& and dtd.is_available='Y' and BTDV.grp_id=& and btdv.buss_column_id not in (select COL_ID from PRG_GRP_DIM_TAB_DETAILS)"}, {"insertGrpDimMembers", " INSERT INTO PRG_GRP_DIM_MEMBER (MEMBER_ID, MEMBER_NAME, DIM_ID, DIM_TAB_ID, USE_DENOM_TABLE, DENOM_TAB_ID, DENOM_QUERY,"
            + "MEMBER_DESC,MEMBER_ORDER_BY,ISNULLVALUE) VALUES(&,'&',&,&,'&',(SELECT distinct buss_table_id "
            + "FROM prg_grp_buss_table_master_view WHERE db_table_id='&' and grp_id=&),'&', '&','&','&')"}, {"insertGrpDimMembers1", " INSERT INTO PRG_GRP_DIM_MEMBER ( MEMBER_NAME, DIM_ID, DIM_TAB_ID, USE_DENOM_TABLE, DENOM_TAB_ID, DENOM_QUERY,"
            + "MEMBER_DESC,MEMBER_ORDER_BY,ISNULLVALUE) VALUES('&',&,&,'&',(SELECT distinct buss_table_id "
            + "FROM prg_grp_buss_table_master_view WHERE db_table_id='&' and grp_id=&),'&', '&','&','&')"}, {"getQryDimMbrsInfo", "SELECT QDM.member_name,QDM.use_denom_table,QDM.denom_tab_id,QDM.denom_query,qdm.dim_tab_id, qdm.member_id, qdm.member_order_by, qdm.isnullvalue  "
            + "FROM PRG_QRY_DIM_TABLES QDT, PRG_QRY_DIM_MEMBER QDM WHERE qdt.dim_id= qdm.dim_id AND qdt.dim_tab_id= qdm.dim_tab_id AND qdt.dim_id=& and QDM.member_name not in (select MEMBER_NAME from PRG_GRP_DIM_MEMBER where dim_id=&)"}, {"insertGrpDimMembersDtls", "insert into PRG_GRP_DIM_MEMBER_DETAILS(MEM_DETAIL_ID, MEM_ID, COL_ID, COL_TYPE)"
            + " select (PRG_GRP_DIM_MEMBER_DETAILS_SEQ.nextval) as mem_detail_id,& as mem_id,btdv.buss_column_id,"
            + "dmd.col_type FROM PRG_QRY_DIM_MEMBER_DETAILS dmd, prg_grp_buss_table_dtls_view btdv where dmd.col_id= btdv.db_column_id and  dmd.mem_id=& and btdv.grp_id=&"}, {"insertGrpDimMembersDtls1", "insert into PRG_GRP_DIM_MEMBER_DETAILS( MEM_ID, COL_ID, COL_TYPE)"
            + " select (select LAST_INSERT_ID(MEMBER_ID) FROM PRG_GRP_DIM_MEMBER ORDER BY 1 DESC LIMIT 1) as mem_id,btdv.buss_column_id,"
            + "dmd.col_type FROM PRG_QRY_DIM_MEMBER_DETAILS dmd, prg_grp_buss_table_dtls_view btdv where dmd.col_id= btdv.db_column_id and  dmd.mem_id=& and btdv.grp_id=&"}, {"getQryDimRel", "select description, is_default, rel_name, rel_id from prg_qry_dim_rel where dim_id='&'"},
        {"insertGrpDimRel", "insert into PRG_GRP_DIM_REL (REL_ID, DIM_ID, DESCRIPTION, IS_DEFAULT, REL_NAME) select (PRG_GRP_DIM_REL_SEQ.nextval),"
            + "&,description, is_default, rel_name from prg_qry_dim_rel where dim_id='&' and rel_id='&'  "}, {"getQryDimRelDtls", "SELECT rel_level, mem_id FROM PRG_QRY_DIM_MBR_REL_DTLS_VIEW where dim_id='&' and rel_id='&' AND rel_level NOT IN (SELECT REL_LEVEL FROM PRG_GRP_DIM_REL_DETAILS WHERE rel_id= & )"}, {"insertGrpDimRelDtls", "INSERT INTO PRG_GRP_DIM_REL_DETAILS(REL_ID, MEM_ID, REL_LEVEL) SELECT &,&,rel_level "
            + "FROM PRG_QRY_DIM_REL_DETAILS where rel_id='&' and mem_id='&'"}, {"getBussDimInfoByGrpId", "SELECT DISTINCT gd.dim_id,gdm.member_name  as disp_name,gdt.dim_tab_id,gdt.tab_id,gd.dim_name,gdm.member_id,gdm.member_name ,  gdm.use_denom_table    ,  gd.default_hierarchy_id,    gdm.denom_tab_id         FROM prg_grp_dimensions gd,   prg_grp_dim_tables gdt     ,  prg_grp_dim_member gdm   WHERE gd.dim_id =gdt.dim_id AND gdm.dim_id    = gd.dim_id AND gdm.dim_tab_id= gdt.dim_tab_id AND gd.grp_id     ='&' AND gdm.dim_id='&' and gdm.member_id not in(select MEMBER_ID from PRG_USER_SUB_FOLDER_TABLES where DIM_ID=& and SUB_FOLDER_ID='&') ORDER BY gd.dim_id"}, {"addUserSubFolderTablesForDimensions", "insert into PRG_USER_SUB_FOLDER_TABLES(SUB_FOLDER_TAB_ID,SUB_FOLDER_ID, BUSS_TABLE_ID, IS_DIMENSION, IS_FACT, IS_BUCKET, "
            + "DISP_NAME, DIM_ID,DIM_TAB_ID ,DIM_NAME,MEMBER_ID,MEMBER_NAME,USE_DENOM_TABLE,DEFAULT_HIERARCHY_ID,DENOM_TAB_ID,USE_REPORT_MEMBER,USE_REPORT_DIM_MEMBER,TABLE_DISP_NAME,TABLE_TOOLTIP_NAME) values ('&','&','&','&','&','&','&','&','&','&','&','&','&','&','&','Y','Y','&','&')"} //end
        , {"addUserSubFolderElementsMysql", "INSERT INTO PRG_USER_SUB_FOLDER_ELEMENTS (SUB_FOLDER_ID, BUSS_TABLE_ID, BUSS_COL_ID, BUSS_COL_NAME, USER_COL_NAME,"
            + " USER_COL_DESC, USER_COL_TYPE, SUB_FOLDER_TAB_ID,REF_ELEMENT_ID,REF_ELEMENT_TYPE,DEFAULT_AGGREGATION,USE_REPORT_FLAG,Display_Formula) values (&,&,&,'&','&','&','&',&,&,&,'&','&','&')"} //               commented by Nazneen
        //             ,{"getUserSubFolderElements","SELECT a.BUSS_TABLE_ID, a.buss_column_id,a.column_name,a.column_disp_name,a.column_display_desc, " +
        //                " a.column_type ,1 AS REF_ELEMENT_TYPE,a.default_aggregation,a.display_formula FROM PRG_GRP_BUSS_TABLE_DETAILS a " +
        //                "where  a.buss_table_id='&' and a.buss_column_id not in (select BUSS_COL_ID from PRG_USER_SUB_FOLDER_ELEMENTS where SUB_FOLDER_ID=&)"}
        //               , {"addUserSubFolderElements", "INSERT INTO PRG_USER_SUB_FOLDER_ELEMENTS (ELEMENT_ID, SUB_FOLDER_ID, BUSS_TABLE_ID, BUSS_COL_ID, BUSS_COL_NAME, USER_COL_NAME,"
        //            + " USER_COL_DESC, USER_COL_TYPE, SUB_FOLDER_TAB_ID,REF_ELEMENT_ID,REF_ELEMENT_TYPE,DEFAULT_AGGREGATION,USE_REPORT_FLAG,Display_Formula) SELECT (PRG_USER_SUB_FLDR_ELEMENTS_SEQ.NEXTVAL) as ELEMENT_ID,"
        //            + "& as SUB_FOLDER_ID,a.BUSS_TABLE_ID, a.buss_column_id, a.column_name,a.column_disp_name,a.column_display_desc,"
        //            + "a.column_type,& as SUB_FOLDER_TAB_ID,(PRG_USER_SUB_FLDR_ELEMENTS_SEQ.CURRVAL),1 AS REF_ELEMENT_TYPE,a.default_aggregation,'Y',a.display_formula FROM PRG_GRP_BUSS_TABLE_DETAILS a "
        //            + "where  a.buss_table_id='&' and a.buss_column_id not in (select BUSS_COL_ID from PRG_USER_SUB_FOLDER_ELEMENTS where SUB_FOLDER_ID=&)"}
        , {"getAllMemRel", "select d.rel_id,d.mem_id, d.rel_level, pd.dim_id from prg_grp_dim_rel_details d,prg_grp_dim_rel pd where "
            + " d.rel_id in (select rel_id from prg_grp_dim_rel where dim_id in(SELECT DISTINCT gd.dim_id from prg_grp_dimensions gd,"
            + " prg_grp_dim_tables gdt,  prg_grp_dim_member gdm ,prg_grp_buss_table pgb  WHERE gd.dim_id =gdt.dim_id AND "
            + " gdm.dim_id    = gd.dim_id AND gdm.dim_tab_id= gdt.dim_tab_id AND gd.grp_id ='&' and pgb.buss_table_id=gdt.tab_id and "
            + " pgb.buss_type in('Table','Query')) and is_default='Y')  and pd.rel_id= d.rel_id and d.mem_id not in (select MEMBER_ID from prg_grp_role_custom_drill) order by rel_id,rel_level"}, {"getRoleCustomDrill", "SELECT DISTINCT gd.dim_id,gdm.member_name as disp_name,gdt.dim_tab_id,gdt.tab_id,gd.dim_name,gdm.member_id,"
            + " gdm.member_name ,gdm.use_denom_table , gd.default_hierarchy_id, gdm.denom_tab_id FROM "
            + " prg_grp_dimensions gd,prg_grp_dim_tables gdt , prg_grp_dim_member gdm ,prg_grp_buss_table pgb "
            + " WHERE gd.dim_id =gdt.dim_id AND gdm.dim_id = gd.dim_id AND gdm.dim_tab_id= gdt.dim_tab_id AND "
            + "gd.grp_id ='&' and pgb.buss_table_id=gdt.tab_id and pgb.buss_type in('Table','Query') and gd.dim_name!='Time' and gdm.member_id not in (select MEMBER_ID from prg_grp_role_custom_drill) ORDER BY gd.dim_id"} // ,{"addRoleCustomDrill","insert into prg_grp_role_custom_drill(CUSTOM_DRILL_ID,FOLDER_ID,SUB_FOLDER_ID,MEMBER_ID,CHILD_MEMBER_ID) values(PRG_CUST_DRILL_SEQ.nextVal,'&','&','&','&')"}
        , {"getSequenceNumber", "select &.nextval from dual"}, {"addRoleCustomDrill", "insert into prg_grp_role_custom_drill(CUSTOM_DRILL_ID,FOLDER_ID,SUB_FOLDER_ID,MEMBER_ID,CHILD_MEMBER_ID,DRILL_ID) values(PRG_CUST_DRILL_SEQ.nextVal,'&','&','&','&','&')"} //added by sunita rai for partial publish additional column of  dimention
        , {"insertinUserAllInfoDetails", "INSERT INTO PRG_USER_ALL_INFO_DETAILS(GRP_ID ,FOLDER_ID ,FOLDER_NAME ,SUB_FOLDER_ID ,SUB_FOLDER_NAME ,SUB_FOLDER_TYPE ,SUB_FOLDER_TAB_ID,IS_DIMENSION"
            + ", IS_FACT ,IS_BUCKET , DISP_NAME , DIM_ID ,DIM_TAB_ID ,DIM_NAME ,ELEMENT_ID ,BUSS_TABLE_ID ,BUSS_COL_ID ,BUSS_COL_NAME ,USER_COL_NAME ,USER_COL_DESC,USER_COL_TYPE , REF_ELEMENT_ID"
            + " ,REF_ELEMENT_TYPE ,MEMBER_ID ,MEMBER_NAME ,BUSS_TABLE_NAME ,CONNECTION_ID ,AGGREGATION_TYPE ,ACTUAL_COL_FORMULA,USE_REPORT_FLAG,REFFERED_ELEMENTS,Display_Formula,TABLE_DISP_NAME,"
            + "TABLE_TOOLTIP_NAME)SELECT busstab.grp_id ,puf.FOLDER_ID ,puf.FOLDER_NAME ,pufd.SUB_FOLDER_ID ,pufd.SUB_FOLDER_NAME ,pufd.SUB_FOLDER_TYPE ,pusft.SUB_FOLDER_TAB_ID ,pusft.IS_DIMENSION "
            + ",pusft.IS_FACT ,pusft.IS_BUCKET ,pusft.DISP_NAME ,pusft.DIM_ID ,pusft.DIM_TAB_ID ,pusft.DIM_NAME ,pusfe.ELEMENT_ID ,pusfe.BUSS_TABLE_ID ,pusfe.BUSS_COL_ID ,pusfe.BUSS_COL_NAME ,pusfe.USER_COL_NAME "
            + ",pusfe.USER_COL_DESC,pusfe.USER_COL_TYPE ,pusfe.ref_element_id ,pusfe.ref_element_type ,pusft.member_id ,pusft.member_name,busstab.buss_table_name,connTab.conn_id,bussdet.default_aggregation,bussdet.ACTUAL_COL_FORMULA"
            + ",pusfe.use_report_flag,bussdet.REFFERED_ELEMENTS,bussdet.display_formula,NVL(pusft.TABLE_DISP_NAME,pusft.DISP_NAME),NVL(pusft.TABLE_TOOLTIP_NAME,pusft.DISP_NAME)FROM PRG_USER_FOLDER puf ,PRG_USER_FOLDER_DETAIL pufd ,PRG_USER_SUB_FOLDER_TABLES pusft "
            + ",PRG_USER_SUB_FOLDER_ELEMENTS pusfe,PRG_GRP_BUSS_TABLE bussTab,PRG_GRP_BUSS_TABLE_DETAILS bussDet,(SELECT MIN(CONNECTION_ID) conn_id,buss_table_id FROM prg_grp_buss_table_src GROUP BY buss_table_id) connTab WHERE puf.folder_id= pufd.folder_id AND pufd.SUB_FOLDER_ID=pusft.SUB_FOLDER_ID "
            + "AND pusfe.sub_folder_tab_id=pusft.sub_folder_tab_id AND busstab.buss_table_id  = pusft.buss_table_id AND bussdet.buss_column_id = pusfe.buss_col_id AND connTab.buss_table_id  = pusft.buss_table_id AND pusfe.buss_col_id!=0 AND puf.folder_id  IN(&) "
            + "and pusft.BUSS_TABLE_ID=& AND pusfe.use_report_flag='Y' AND USE_REPORT_DIM_MEMBER='Y' and pusfe.ELEMENT_ID not in (select ELEMENT_ID from PRG_USER_ALL_INFO_DETAILS) ORDER BY puf.folder_id,pufd.SUB_FOLDER_NAME,pusft.SUB_FOLDER_TAB_ID"}, {"insertinUserAllInfoDetailsMysql", "INSERT INTO PRG_USER_ALL_INFO_DETAILS(GRP_ID ,FOLDER_ID ,FOLDER_NAME ,SUB_FOLDER_ID ,SUB_FOLDER_NAME ,SUB_FOLDER_TYPE ,SUB_FOLDER_TAB_ID,IS_DIMENSION"
            + ", IS_FACT ,IS_BUCKET , DISP_NAME , DIM_ID ,DIM_TAB_ID ,DIM_NAME ,ELEMENT_ID ,BUSS_TABLE_ID ,BUSS_COL_ID ,BUSS_COL_NAME ,USER_COL_NAME ,USER_COL_DESC,USER_COL_TYPE , REF_ELEMENT_ID"
            + " ,REF_ELEMENT_TYPE ,MEMBER_ID ,MEMBER_NAME ,BUSS_TABLE_NAME ,CONNECTION_ID ,AGGREGATION_TYPE ,ACTUAL_COL_FORMULA,USE_REPORT_FLAG,REFFERED_ELEMENTS,Display_Formula,TABLE_DISP_NAME,"
            + "TABLE_TOOLTIP_NAME)SELECT busstab.grp_id ,puf.FOLDER_ID ,puf.FOLDER_NAME ,pufd.SUB_FOLDER_ID ,pufd.SUB_FOLDER_NAME ,pufd.SUB_FOLDER_TYPE ,pusft.SUB_FOLDER_TAB_ID ,pusft.IS_DIMENSION "
            + ",pusft.IS_FACT ,pusft.IS_BUCKET ,pusft.DISP_NAME ,pusft.DIM_ID ,pusft.DIM_TAB_ID ,pusft.DIM_NAME ,pusfe.ELEMENT_ID ,pusfe.BUSS_TABLE_ID ,pusfe.BUSS_COL_ID ,pusfe.BUSS_COL_NAME ,pusfe.USER_COL_NAME "
            + ",pusfe.USER_COL_DESC,pusfe.USER_COL_TYPE ,pusfe.ref_element_id ,pusfe.ref_element_type ,pusft.member_id ,pusft.member_name,busstab.buss_table_name,connTab.conn_id,bussdet.default_aggregation,bussdet.ACTUAL_COL_FORMULA"
            + ",pusfe.use_report_flag,bussdet.REFFERED_ELEMENTS,bussdet.display_formula,ifnull(pusft.TABLE_DISP_NAME,pusft.DISP_NAME),ifnull(pusft.TABLE_TOOLTIP_NAME,pusft.DISP_NAME)FROM PRG_USER_FOLDER puf ,PRG_USER_FOLDER_DETAIL pufd ,PRG_USER_SUB_FOLDER_TABLES pusft "
            + ",PRG_USER_SUB_FOLDER_ELEMENTS pusfe,PRG_GRP_BUSS_TABLE bussTab,PRG_GRP_BUSS_TABLE_DETAILS bussDet,(SELECT MIN(CONNECTION_ID) conn_id,buss_table_id FROM prg_grp_buss_table_src GROUP BY buss_table_id) connTab WHERE puf.folder_id= pufd.folder_id AND pufd.SUB_FOLDER_ID=pusft.SUB_FOLDER_ID "
            + "AND pusfe.sub_folder_tab_id=pusft.sub_folder_tab_id AND busstab.buss_table_id  = pusft.buss_table_id AND bussdet.buss_column_id = pusfe.buss_col_id AND connTab.buss_table_id  = pusft.buss_table_id AND pusfe.buss_col_id!=0 AND puf.folder_id  IN(&) "
            + "and pusft.BUSS_TABLE_ID=& AND pusfe.use_report_flag='Y' AND USE_REPORT_DIM_MEMBER='Y' and pusfe.ELEMENT_ID not in (select ELEMENT_ID from PRG_USER_ALL_INFO_DETAILS) ORDER BY puf.folder_id,pufd.SUB_FOLDER_NAME,pusft.SUB_FOLDER_TAB_ID"}, {"insertintoallAdimDetails", "INSERT INTO PRG_USER_ALL_ADIM_DETAILS(INFO_FOLDER_ID,INFO_ELEMENT_ID,INFO_BUSS_COL_ID,REL_LEVEL,INFO_DIM_ID,INFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME)"
            + "SELECT info.folder_id info_folder_id,info.element_id info_element_id,info.buss_col_id info_buss_col_id,NVL(reld.rel_level,1) rel_level,info.dim_id info_dim_id,"
            + "info.dim_name info_dim_name,info.member_id info_member_id,info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info ,"
            + "prg_grp_dim_rel relm ,prg_grp_dim_rel_details reld WHERE info.member_id = reld.mem_id(+) AND info.dim_id = relm.dim_id(+)"
            + "AND info.member_id  IS NOT NULL AND info.folder_id  IN(&) and info.BUSS_TABLE_ID=& and info.member_id not in (select INFO_MEMBER_ID from PRG_USER_ALL_ADIM_DETAILS)"}, {"insertintoallAdimDetailsMysql", "INSERT INTO PRG_USER_ALL_ADIM_DETAILS(INFO_FOLDER_ID,INFO_ELEMENT_ID,INFO_BUSS_COL_ID,REL_LEVEL,INFO_DIM_ID,INFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME)"
            + "SELECT info.folder_id info_folder_id,info.element_id info_element_id,info.buss_col_id info_buss_col_id,ifnull(reld.rel_level,1) rel_level,info.dim_id info_dim_id,"
            + "info.dim_name info_dim_name,info.member_id info_member_id,info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info "
            + "LEFT OUTER JOIN prg_grp_dim_rel relm ON ( info.dim_id = relm.dim_id )LEFT OUTER JOIN prg_grp_dim_rel_details reld ON ( info.member_id = reld.mem_id) WHERE info.folder_id IN (&) and info.BUSS_TABLE_ID =& AND info.member_id IS NOT NULL"
            + " and info.member_id not in (select INFO_MEMBER_ID from PRG_USER_ALL_ADIM_DETAILS)"}, {"insertintoallAdimKeyValueElements", "INSERT INTO PRG_USER_ALL_ADIM_KEY_VAL_ELE(LEVEL1,KEY_ELEMENT_ID,KEY_COL_TYPE,VAL_ELEMENT_ID,KEY_BUSS_COL_ID,VAL_BUSS_COL_ID,KEY_BUSS_COL_NAME,VAL_BUSS_COL_NAME,"
            + "KEY_BUSS_TABLE_ID,VAL_BUSS_TABLE_ID,VAL_COL_TYPE,KEY_MEMBER_NAME,VAL_MEMBER_NAME,KEY_SUB_FOLDER_NAME,VAL_SUB_FOLDER_NAME,KEY_SUB_FOLDER_ID,VAL_SUB_FOLDER_ID,KEY_DISP_NAME,"
            + "KEY_DIM_ID,KEY_DIM_NAME, VAL_DISP_NAME,VAL_DIM_ID,VAL_DIM_NAME,KEY_FOLDER_ID,KEY_FOLDER_NAME,REL_NAME,IS_DEFAULT)"
            + "SELECT NVL(reld.rel_level,1) level1,key1.element_id Key_element_id,key1.USER_COL_TYPE Key_col_type,val1.ref_element_id val_element_id ,key1.buss_col_id key_buss_col_id ,"
            + "val1.buss_col_id val_buss_col_id ,key1.buss_col_name Key_buss_col_name,val1.buss_col_name val_buss_col_name ,key1.buss_table_id Key_buss_table_id,val1.buss_table_id val_buss_table_id ,"
            + "val1.USER_COL_TYPE val_col_type,key1.member_name key_member_name ,val1.member_name val_member_name ,key1.SUB_FOLDER_NAME key_SUB_FOLDER_NAME,val1.SUB_FOLDER_NAME val_SUB_FOLDER_NAME ,"
            + "key1.SUB_FOLDER_ID key_SUB_FOLDER_ID,val1.SUB_FOLDER_ID val_SUB_FOLDER_ID ,key1.disp_name key_disp_name ,key1.dim_id key_dim_id,key1.dim_name key_dim_name,val1.disp_name val_disp_name,"
            + "val1.dim_id val_dim_id,val1.dim_name val_dim_name ,key1.folder_id key_folder_id ,key1.folder_name key_folder_name ,relm.rel_name ,relm.is_default FROM PRG_GRP_DIM_MAP_KEY_VALUE map ,"
            + "PRG_USER_ALL_INFO_DETAILS key1 ,PRG_USER_ALL_INFO_DETAILS val1 ,prg_grp_dim_rel relm ,prg_grp_dim_rel_details reld WHERE map.key1= key1.buss_col_id"
            + " AND key1.member_id = map.key_mem_id AND val1.member_id   = map.mem_mem_id AND val1.buss_col_id = map.value1 AND key1.member_id   = reld.mem_id(+) AND key1.dim_id= relm.dim_id(+)"
            + "AND key1.folder_id  IN(&) AND val1.folder_id IN(&) and key1.BUSS_TABLE_ID=& and val1.BUSS_TABLE_ID=& and key1.element_id not in (select KEY_ELEMENT_ID from PRG_USER_ALL_ADIM_KEY_VAL_ELE) ORDER BY 1"}, {"insertintoallAdimKeyValueElementsMysql", "INSERT INTO PRG_USER_ALL_ADIM_KEY_VAL_ELE(LEVEL1,KEY_ELEMENT_ID,KEY_COL_TYPE,VAL_ELEMENT_ID,KEY_BUSS_COL_ID,VAL_BUSS_COL_ID,KEY_BUSS_COL_NAME,VAL_BUSS_COL_NAME,"
            + "KEY_BUSS_TABLE_ID,VAL_BUSS_TABLE_ID,VAL_COL_TYPE,KEY_MEMBER_NAME,VAL_MEMBER_NAME,KEY_SUB_FOLDER_NAME,VAL_SUB_FOLDER_NAME,KEY_SUB_FOLDER_ID,VAL_SUB_FOLDER_ID,KEY_DISP_NAME,"
            + "KEY_DIM_ID,KEY_DIM_NAME, VAL_DISP_NAME,VAL_DIM_ID,VAL_DIM_NAME,KEY_FOLDER_ID,KEY_FOLDER_NAME,REL_NAME,IS_DEFAULT)"
            + "SELECT ifnull(reld.rel_level,1) level1,key1.element_id Key_element_id,key1.USER_COL_TYPE Key_col_type,val1.ref_element_id val_element_id ,key1.buss_col_id key_buss_col_id ,"
            + "val1.buss_col_id val_buss_col_id ,key1.buss_col_name Key_buss_col_name,val1.buss_col_name val_buss_col_name ,key1.buss_table_id Key_buss_table_id,val1.buss_table_id val_buss_table_id ,"
            + "val1.USER_COL_TYPE val_col_type,key1.member_name key_member_name ,val1.member_name val_member_name ,key1.SUB_FOLDER_NAME key_SUB_FOLDER_NAME,val1.SUB_FOLDER_NAME val_SUB_FOLDER_NAME ,"
            + "key1.SUB_FOLDER_ID key_SUB_FOLDER_ID,val1.SUB_FOLDER_ID val_SUB_FOLDER_ID ,key1.disp_name key_disp_name ,key1.dim_id key_dim_id,key1.dim_name key_dim_name,val1.disp_name val_disp_name,"
            + "val1.dim_id val_dim_id,val1.dim_name val_dim_name ,key1.folder_id key_folder_id ,key1.folder_name key_folder_name ,relm.rel_name ,relm.is_default FROM PRG_GRP_DIM_MAP_KEY_VALUE map "
            + "INNER JOIN PRG_USER_ALL_INFO_DETAILS key1 ON (map.key1= key1.buss_col_id AND key1.member_id = map.key_mem_id)INNER JOIN PRG_USER_ALL_INFO_DETAILS val1 ON ( val1.member_id = map.mem_mem_id AND val1.buss_col_id = map.value1) LEFT OUTER JOIN prg_grp_dim_rel relm ON (key1.dim_id = relm.dim_id) LEFT OUTER JOIN prg_grp_dim_rel_details reld ON (key1.member_id= reld.mem_id)  WHERE "
            + " key1.folder_id IN (&) AND val1.folder_id IN (&) and key1.BUSS_TABLE_ID =& and val1.BUSS_TABLE_ID =&  and key1.element_id not in (select KEY_ELEMENT_ID from PRG_USER_ALL_ADIM_KEY_VAL_ELE) ORDER BY 1"}, {"insertintoallAdimMasterdetails", "INSERT INTO PRG_USER_ALL_ADIM_MASTER(INFO_FOLDER_ID,REL_LEVEL,INFO_DIM_ID,INFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME)"
            + "SELECT DISTINCT info.folder_id info_folder_id,NVL(reld.rel_level,1) rel_level,info.dim_id info_dim_id,info.dim_name info_dim_name,info.member_id info_member_id,info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info ,"
            + "prg_grp_dim_rel relm ,prg_grp_dim_rel_details reld WHERE info.member_id = reld.mem_id(+)AND info.dim_id= relm.dim_id(+)"
            + "AND info.member_id  IS NOT NULL AND info.folder_id  IN(&) and info.BUSS_TABLE_ID=&  and info.member_id not in (select INFO_MEMBER_ID from PRG_USER_ALL_ADIM_MASTER)"}, {"insertintoallAdimMasterdetailsMysql", "INSERT INTO PRG_USER_ALL_ADIM_MASTER(REL_LEVEL,INFO_DIM_ID,INFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME) SELECT DISTINCT COALESCE(reld.rel_level,1) rel_level,info.dim_id info_dim_id,info.dim_name info_dim_name,info.member_id info_member_id,info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info LEFT OUTER JOIN prg_grp_dim_rel relm"
            + " ON ( info.dim_id = relm.dim_id ) LEFT OUTER JOIN prg_grp_dim_rel_details reld ON (info.member_id = reld.mem_id) WHERE info.member_id IS NOT NULL AND info.folder_id  IN (&) and info.BUSS_TABLE_ID =&"}, {"insertallDdimMasterDetails", "INSERT INTO PRG_USER_ALL_DDIM_MASTER(INFO_FOLDER_ID,REL_LEVEL,INFO_DIM_ID,INFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME) SELECT DISTINCT info.folder_id info_folder_id,COALESCE(reld.rel_level,1) rel_level,info.dim_id info_dim_id,info.dim_name info_dim_name,info.member_id info_member_id,info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info"
            + " LEFT OUTER JOIN prg_grp_dim_rel relm ON ( info.dim_id= relm.dim_id AND relm.is_default ='Y' ) LEFT OUTER JOIN prg_grp_dim_rel_details reld ON(info.member_id= reld.mem_id) WHERE info.member_id IS NOT NULL AND info.folder_id    IN (&) and info.BUSS_TABLE_ID =&  and info.member_id not in (select INFO_MEMBER_ID from PRG_USER_ALL_ADIM_MASTER)"}, {"insertallDdimDetails", "INSERT INTO PRG_USER_ALL_DDIM_DETAILS(INFO_FOLDER_ID,INFO_ELEMENT_ID,INFO_BUSS_COL_ID,REL_LEVEL,INFO_DIM_ID,IMFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME)"
            + "SELECT info.folder_id info_folder_id,info.element_id info_element_id,info.buss_col_id info_buss_col_id,NVL(reld.rel_level,1) rel_level,info.dim_id info_dim_id,info.dim_name imfo_dim_name,"
            + "info.member_id info_member_id,info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info ,prg_grp_dim_rel relm ,prg_grp_dim_rel_details reld WHERE info.member_id   = reld.mem_id(+)"
            + "AND info.dim_id = relm.dim_id(+) AND relm.is_default(+) ='Y' AND info.member_id    IS NOT NULL AND info.folder_id    IN(&) and info.BUSS_TABLE_ID=& and info.element_id not in (select INFO_ELEMENT_ID from PRG_USER_ALL_DDIM_DETAILS)"}, {"insertallDdimkeyValueElement", "INSERT INTO PRG_USER_ALL_DDIM_KEY_VAL_ELE(LEVEL1,KEY_ELEMENT_ID,KEY_COL_TYPE,VAL_ELEMENT_ID,KEY_BUSS_COL_ID,VAL_BUSS_COL_ID,KEY_BUSS_COL_NAME,VAL_BUSS_COL_NAME,"
            + "KEY_BUSS_TABLE_ID,VAL_BUSS_TABLE_ID,VAL_COL_TYPE,KEY_MEMBER_NAME,VAL_MEMBER_NAME,KEY_SUB_FOLDER_ID,VAL_SUB_FOLDER_ID,KEY_SUB_FOLDER_NAME,VAL_SUB_FOLDER_NAME,KEY_DISP_NAME,KEY_DIM_ID,"
            + "KEY_DIM_NAME,VAL_DISP_NAME,VAL_DIM_ID,VAL_DIM_NAME,KEY_FOLDER_ID,KEY_FOLDER_NAME,REL_NAME,IS_DEFAULT)"
            + "SELECT NVL(reld.rel_level,1) level1,key1.element_id Key_element_id,key1.USER_COL_TYPE Key_col_type,val1.ref_element_id val_element_id ,key1.buss_col_id key_buss_col_id ,val1.buss_col_id val_buss_col_id ,"
            + "key1.buss_col_name Key_buss_col_name,val1.buss_col_name val_buss_col_name ,key1.buss_table_id Key_buss_table_id,val1.buss_table_id val_buss_table_id ,val1.USER_COL_TYPE val_col_type,"
            + "key1.member_name key_member_name ,val1.member_name val_member_name ,key1.SUB_FOLDER_id key_SUB_FOLDER_id,val1.SUB_FOLDER_id val_SUB_FOLDER_id ,key1.SUB_FOLDER_NAME key_SUB_FOLDER_NAME,"
            + "val1.SUB_FOLDER_NAME val_SUB_FOLDER_NAME ,key1.disp_name key_disp_name ,key1.dim_id key_dim_id,key1.dim_name key_dim_name,val1.disp_name val_disp_name,val1.dim_id val_dim_id,"
            + "val1.dim_name val_dim_name ,key1.folder_id key_folder_id ,key1.folder_name key_folder_name,relm.rel_name,relm.is_default FROM PRG_GRP_DIM_MAP_KEY_VALUE map ,"
            + "PRG_USER_ALL_INFO_DETAILS key1 ,PRG_USER_ALL_INFO_DETAILS val1 ,prg_grp_dim_rel relm ,prg_grp_dim_rel_details reld WHERE map.key1= key1.buss_col_id AND key1.member_id= map.key_mem_id"
            + " AND val1.member_id= map.mem_mem_id AND val1.buss_col_id= map.value1 AND key1.member_id = reld.mem_id(+) AND key1.dim_id= relm.dim_id(+) AND relm.is_default(+) ='Y'"
            + "AND key1.folder_id IN(&) AND val1.folder_id IN(&) and key1.BUSS_TABLE_ID=& and val1.BUSS_TABLE_ID=& and key1.element_id not in (select KEY_ELEMENT_ID from PRG_USER_ALL_DDIM_KEY_VAL_ELE) ORDER BY 1"}, {"insertallDdimMasterDetails", "INSERT INTO PRG_USER_ALL_DDIM_MASTER(INFO_FOLDER_ID,REL_LEVEL,INFO_DIM_ID,INFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME)"
            + "SELECT DISTINCT info.folder_id info_folder_id,NVL(reld.rel_level,1) rel_level,info.dim_id info_dim_id,info.dim_name info_dim_name,info.member_id info_member_id,"
            + "info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info ,prg_grp_dim_rel relm ,prg_grp_dim_rel_details reld WHERE info.member_id= reld.mem_id(+)"
            + "AND info.dim_id= relm.dim_id(+) AND relm.is_default(+) ='Y' AND info.member_id IS NOT NULL AND info.folder_id IN(&) and info.BUSS_TABLE_ID=& and INFO.MEMBER_ID not in (select INFO_MEMBER_ID from PRG_USER_ALL_DDIM_MASTER)"}, {"insertallDdimDetailsMysql", "INSERT INTO PRG_USER_ALL_DDIM_DETAILS(INFO_FOLDER_ID,INFO_ELEMENT_ID,INFO_BUSS_COL_ID,REL_LEVEL,INFO_DIM_ID,IMFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME)"
            + "SELECT info.folder_id info_folder_id,info.element_id info_element_id,info.buss_col_id info_buss_col_id,ifnull(reld.rel_level,1) rel_level,info.dim_id info_dim_id,info.dim_name imfo_dim_name,"
            + "info.member_id info_member_id,info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info LEFT OUTER JOIN prg_grp_dim_rel relm ON ( info.dim_id = relm.dim_id ) LEFT OUTER JOIN prg_grp_dim_rel_details reld ON ( info.member_id = reld.mem_id)  WHERE "
            + "relm.is_default ='Y' AND info.member_id IS NOT NULL AND info.folder_id IN (&) and info.BUSS_TABLE_ID =&  and info.element_id not in (select INFO_ELEMENT_ID from PRG_USER_ALL_DDIM_DETAILS)"}, {"insertallDdimkeyValueElementMysql", "INSERT INTO PRG_USER_ALL_DDIM_KEY_VAL_ELE(LEVEL1,KEY_ELEMENT_ID,KEY_COL_TYPE,VAL_ELEMENT_ID,KEY_BUSS_COL_ID,VAL_BUSS_COL_ID,KEY_BUSS_COL_NAME,VAL_BUSS_COL_NAME,"
            + "KEY_BUSS_TABLE_ID,VAL_BUSS_TABLE_ID,VAL_COL_TYPE,KEY_MEMBER_NAME,VAL_MEMBER_NAME,KEY_SUB_FOLDER_ID,VAL_SUB_FOLDER_ID,KEY_SUB_FOLDER_NAME,VAL_SUB_FOLDER_NAME,KEY_DISP_NAME,KEY_DIM_ID,"
            + "KEY_DIM_NAME,VAL_DISP_NAME,VAL_DIM_ID,VAL_DIM_NAME,KEY_FOLDER_ID,KEY_FOLDER_NAME,REL_NAME,IS_DEFAULT)"
            + "SELECT ifnull(reld.rel_level,1) level1,key1.element_id Key_element_id,key1.USER_COL_TYPE Key_col_type,val1.ref_element_id val_element_id ,key1.buss_col_id key_buss_col_id ,val1.buss_col_id val_buss_col_id ,"
            + "key1.buss_col_name Key_buss_col_name,val1.buss_col_name val_buss_col_name ,key1.buss_table_id Key_buss_table_id,val1.buss_table_id val_buss_table_id ,val1.USER_COL_TYPE val_col_type,"
            + "key1.member_name key_member_name ,val1.member_name val_member_name ,key1.SUB_FOLDER_id key_SUB_FOLDER_id,val1.SUB_FOLDER_id val_SUB_FOLDER_id ,key1.SUB_FOLDER_NAME key_SUB_FOLDER_NAME,"
            + "val1.SUB_FOLDER_NAME val_SUB_FOLDER_NAME ,key1.disp_name key_disp_name ,key1.dim_id key_dim_id,key1.dim_name key_dim_name,val1.disp_name val_disp_name,val1.dim_id val_dim_id,"
            + "val1.dim_name val_dim_name ,key1.folder_id key_folder_id ,key1.folder_name key_folder_name,relm.rel_name,relm.is_default FROM PRG_GRP_DIM_MAP_KEY_VALUE map "
            + "INNER JOIN PRG_USER_ALL_INFO_DETAILS key1 ON (map.key1= key1.buss_col_id AND key1.member_id = map.key_mem_id) INNER JOIN PRG_USER_ALL_INFO_DETAILS val1 ON ( val1.member_id = map.mem_mem_id AND val1.buss_col_id = map.value1) LEFT OUTER JOIN prg_grp_dim_rel relm ON (key1.dim_id = relm.dim_id and relm.is_default ='Y') LEFT OUTER JOIN prg_grp_dim_rel_details reld ON (key1.member_id = reld.mem_id) WHERE "
            + "key1.folder_id IN (&) AND val1.folder_id IN (&) and key1.BUSS_TABLE_ID =& and val1.BUSS_TABLE_ID =&  and key1.element_id not in (select KEY_ELEMENT_ID from PRG_USER_ALL_DDIM_KEY_VAL_ELE) ORDER BY 1"}, {"insertallDdimMasterDetailsMysql", "INSERT INTO PRG_USER_ALL_DDIM_MASTER(INFO_FOLDER_ID,REL_LEVEL,INFO_DIM_ID,INFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME) SELECT DISTINCT info.folder_id info_folder_id,COALESCE(reld.rel_level,1) rel_level,info.dim_id info_dim_id,info.dim_name info_dim_name,info.member_id info_member_id,info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info"
            + " LEFT OUTER JOIN prg_grp_dim_rel relm ON ( info.dim_id= relm.dim_id AND relm.is_default ='Y' ) LEFT OUTER JOIN prg_grp_dim_rel_details reld ON(info.member_id= reld.mem_id) WHERE info.member_id IS NOT NULL AND info.folder_id    IN (&) and info.BUSS_TABLE_ID =& and INFO.MEMBER_ID not in (select INFO_MEMBER_ID from PRG_USER_ALL_DDIM_MASTER)"} //end of queries added by sunita rai
        //added by Nazneen for Partial publish in Sql Server
        , {"insertGrpDimMembersDtls2", "insert into PRG_GRP_DIM_MEMBER_DETAILS( MEM_ID, COL_ID, COL_TYPE)"
            + " select (select MAX(MEMBER_ID) FROM PRG_GRP_DIM_MEMBER) as mem_id,btdv.buss_column_id,"
            + "dmd.col_type FROM PRG_QRY_DIM_MEMBER_DETAILS dmd, prg_grp_buss_table_dtls_view btdv where dmd.col_id= btdv.db_column_id and  dmd.mem_id=& and btdv.grp_id=&"}, {"insertinUserAllInfoDetailsSqlServer", "INSERT INTO PRG_USER_ALL_INFO_DETAILS(GRP_ID,FOLDER_ID,FOLDER_NAME,SUB_FOLDER_ID,SUB_FOLDER_NAME,SUB_FOLDER_TYPE ,SUB_FOLDER_TAB_ID,IS_DIMENSION,IS_FACT,IS_BUCKET,DISP_NAME,DIM_ID,DIM_TAB_ID ,DIM_NAME,ELEMENT_ID,BUSS_TABLE_ID,BUSS_COL_ID,BUSS_COL_NAME,USER_COL_NAME ,"
            + " USER_COL_DESC ,USER_COL_TYPE,REF_ELEMENT_ID,REF_ELEMENT_TYPE , MEMBER_ID , MEMBER_NAME , BUSS_TABLE_NAME , CONNECTION_ID , AGGREGATION_TYPE , ACTUAL_COL_FORMULA, USE_REPORT_FLAG,REFFERED_ELEMENTS,Display_Formula,TABLE_DISP_NAME,TABLE_TOOLTIP_NAME) SELECT busstab.grp_id ,puf.FOLDER_ID ,puf.FOLDER_NAME ,pufd.SUB_FOLDER_ID ,pufd.SUB_FOLDER_NAME ,pufd.SUB_FOLDER_TYPE ,pusft.SUB_FOLDER_TAB_ID ,pusft.IS_DIMENSION ,pusft.IS_FACT ,"
            + " pusft.IS_BUCKET,pusft.DISP_NAME,pusft.DIM_ID,pusft.DIM_TAB_ID ,pusft.DIM_NAME , pusfe.ELEMENT_ID ,pusfe.BUSS_TABLE_ID ,pusfe.BUSS_COL_ID ,pusfe.BUSS_COL_NAME , pusfe.USER_COL_NAME ,pusfe.USER_COL_DESC,pusfe.USER_COL_TYPE ,pusfe.ref_element_id ,pusfe.ref_element_type,pusft.member_id ,pusft.member_name,busstab.buss_table_name,connTab.conn_id, bussdet.default_aggregation, bussdet.ACTUAL_COL_FORMULA, pusfe.use_report_flag,bussdet.REFFERED_ELEMENTS,bussdet.display_formula,COALESCE(pusft.TABLE_DISP_NAME,pusft.DISP_NAME),"
            + " COALESCE(pusft.TABLE_TOOLTIP_NAME,pusft.DISP_NAME) FROM PRG_USER_FOLDER puf , PRG_USER_FOLDER_DETAIL pufd ,PRG_USER_SUB_FOLDER_TABLES pusft ,PRG_USER_SUB_FOLDER_ELEMENTS pusfe,PRG_GRP_BUSS_TABLE bussTab ,PRG_GRP_BUSS_TABLE_DETAILS bussDet ,(SELECT MIN(CONNECTION_ID) conn_id,buss_table_id FROM prg_grp_buss_table_src GROUP BY buss_table_id ) connTab WHERE puf.folder_id        = pufd.folder_id "
            + " AND pufd.SUB_FOLDER_ID =pusft.SUB_FOLDER_ID AND pusfe.sub_folder_tab_id=pusft.sub_folder_tab_id AND busstab.buss_table_id  = pusft.buss_table_id AND bussdet.buss_column_id = pusfe.buss_col_id AND connTab.buss_table_id  = pusft.buss_table_id AND pusfe.buss_col_id !=0  AND puf.folder_id IN (&) AND pusft.BUSS_TABLE_ID    = & AND pusfe.use_report_flag  ='Y' AND USE_REPORT_DIM_MEMBER  ='Y' ORDER BY puf.folder_id, pufd.SUB_FOLDER_NAME,pusft.SUB_FOLDER_TAB_ID "}, {"insertintoallAdimDetailsSqlServer", "INSERT INTO PRG_USER_ALL_ADIM_DETAILS (INFO_FOLDER_ID,INFO_ELEMENT_ID,INFO_BUSS_COL_ID,REL_LEVEL,INFO_DIM_ID,INFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME) SELECT info.folder_id info_folder_id,info.element_id info_element_id,info.buss_col_id info_buss_col_id,COALESCE(reld.rel_level,1) rel_level,info.dim_id info_dim_id,info.dim_name info_dim_name,info.member_id info_member_id,info.member_name info_member_name "
            + " FROM PRG_USER_ALL_INFO_DETAILS info LEFT OUTER JOIN prg_grp_dim_rel relm ON ( info.dim_id = relm.dim_id ) LEFT OUTER JOIN prg_grp_dim_rel_details reld ON ( info.member_id   = reld.mem_id) WHERE info.folder_id  IN (&) and info.BUSS_TABLE_ID = & AND info.member_id IS NOT NULL"}, {"insertintoallAdimKeyValueElementsSqlServer", "INSERT INTO PRG_USER_ALL_ADIM_KEY_VAL_ELE (LEVEL1,KEY_ELEMENT_ID, KEY_COL_TYPE, VAL_ELEMENT_ID, KEY_BUSS_COL_ID, VAL_BUSS_COL_ID, KEY_BUSS_COL_NAME, VAL_BUSS_COL_NAME,KEY_BUSS_TABLE_ID,VAL_BUSS_TABLE_ID,  VAL_COL_TYPE,KEY_MEMBER_NAME,VAL_MEMBER_NAME, KEY_SUB_FOLDER_NAME, VAL_SUB_FOLDER_NAME,KEY_SUB_FOLDER_ID, VAL_SUB_FOLDER_ID, KEY_DISP_NAME,KEY_DIM_ID,KEY_DIM_NAME,VAL_DISP_NAME,VAL_DIM_ID, VAL_DIM_NAME,KEY_FOLDER_ID,KEY_FOLDER_NAME, REL_NAME,IS_DEFAULT) SELECT COALESCE(reld.rel_level,1) level1,key1.element_id Key_element_id,key1.USER_COL_TYPE Key_col_type,"
            + "val1.element_id val_element_id ,key1.buss_col_id key_buss_col_id ,val1.buss_col_id val_buss_col_id ,key1.buss_col_name Key_buss_col_name,val1.buss_col_name val_buss_col_name ,key1.buss_table_id Key_buss_table_id, val1.buss_table_id val_buss_table_id ,val1.USER_COL_TYPE val_col_type,key1.member_name key_member_name , val1.member_name val_member_name , key1.SUB_FOLDER_NAME key_SUB_FOLDER_NAME,val1.SUB_FOLDER_NAME val_SUB_FOLDER_NAME ,key1.SUB_FOLDER_ID key_SUB_FOLDER_ID,val1.SUB_FOLDER_ID val_SUB_FOLDER_ID ,key1.disp_name key_disp_name , key1.dim_id key_dim_id, key1.dim_name key_dim_name, val1.disp_name val_disp_name,val1.dim_id val_dim_id,"
            + " val1.dim_name val_dim_name ,key1.folder_id key_folder_id ,key1.folder_name key_folder_name ,relm.rel_name , relm.is_default FROM PRG_GRP_DIM_MAP_KEY_VALUE map INNER JOIN PRG_USER_ALL_INFO_DETAILS key1 ON (map.key1       = key1.buss_col_id AND key1.member_id = map.key_mem_id) INNER JOIN PRG_USER_ALL_INFO_DETAILS val1 ON ( val1.member_id  = map.mem_mem_id AND val1.buss_col_id = map.value1) LEFT OUTER JOIN prg_grp_dim_rel relm ON (key1.dim_id = relm.dim_id) LEFT OUTER JOIN prg_grp_dim_rel_details reld ON (key1.member_id    = reld.mem_id) "
            + "WHERE key1.folder_id  IN (&) AND val1.folder_id IN (&) and key1.BUSS_TABLE_ID = & and val1.BUSS_TABLE_ID = & ORDER BY 1"}, {"insertintoallAdimMasterdetailsSqlServer", "INSERT INTO PRG_USER_ALL_ADIM_MASTER(REL_LEVEL,INFO_DIM_ID,INFO_DIM_NAME,INFO_MEMBER_ID,INFO_MEMBER_NAME) SELECT DISTINCT COALESCE(reld.rel_level,1) rel_level,info.dim_id info_dim_id,info.dim_name info_dim_name,info.member_id info_member_id,     info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info LEFT OUTER JOIN prg_grp_dim_rel relm"
            + " ON ( info.dim_id = relm.dim_id ) LEFT OUTER JOIN prg_grp_dim_rel_details reld ON (info.member_id    = reld.mem_id) WHERE info.member_id IS NOT NULL AND info.folder_id  IN (&) and info.BUSS_TABLE_ID = &"}, {"insertallDdimDetailsSqlServer", "INSERT INTO PRG_USER_ALL_DDIM_DETAILS(INFO_FOLDER_ID,INFO_ELEMENT_ID,INFO_BUSS_COL_ID,REL_LEVEL, INFO_DIM_ID, IMFO_DIM_NAME, INFO_MEMBER_ID,INFO_MEMBER_NAME) SELECT info.folder_id info_folder_id,info.element_id info_element_id,info.buss_col_id info_buss_col_id,isnull(reld.rel_level,1) rel_level,info.dim_id info_dim_id,  info.dim_name imfo_dim_name,info.member_id info_member_id,info.member_name info_member_name "
            + " FROM PRG_USER_ALL_INFO_DETAILS info LEFT OUTER JOIN prg_grp_dim_rel relm ON ( info.dim_id = relm.dim_id ) LEFT OUTER JOIN prg_grp_dim_rel_details reld ON ( info.member_id   = reld.mem_id) WHERE  relm.is_default ='Y' AND info.member_id    IS NOT NULL AND info.folder_id    IN (&) and info.BUSS_TABLE_ID = &"}, {"insertallDdimkeyValueElementSqlServer", "INSERT INTO PRG_USER_ALL_DDIM_KEY_VAL_ELE (LEVEL1,KEY_ELEMENT_ID, KEY_COL_TYPE, VAL_ELEMENT_ID, KEY_BUSS_COL_ID, VAL_BUSS_COL_ID, KEY_BUSS_COL_NAME, VAL_BUSS_COL_NAME,KEY_BUSS_TABLE_ID, VAL_BUSS_TABLE_ID,VAL_COL_TYPE,KEY_MEMBER_NAME, VAL_MEMBER_NAME, KEY_SUB_FOLDER_ID, VAL_SUB_FOLDER_ID, KEY_SUB_FOLDER_NAME,VAL_SUB_FOLDER_NAME,KEY_DISP_NAME, KEY_DIM_ID, KEY_DIM_NAME, VAL_DISP_NAME,VAL_DIM_ID,VAL_DIM_NAME,"
            + "KEY_FOLDER_ID,KEY_FOLDER_NAME, REL_NAME, IS_DEFAULT) SELECT isnull(reld.rel_level,1) level1,key1.element_id Key_element_id,key1.USER_COL_TYPE Key_col_type,val1.ref_element_id val_element_id ,key1.buss_col_id key_buss_col_id ,val1.buss_col_id val_buss_col_id ,key1.buss_col_name Key_buss_col_name, val1.buss_col_name val_buss_col_name ,key1.buss_table_id Key_buss_table_id,val1.buss_table_id val_buss_table_id , val1.USER_COL_TYPE val_col_type,key1.member_name key_member_name ,"
            + "val1.member_name val_member_name ,key1.SUB_FOLDER_id key_SUB_FOLDER_id, val1.SUB_FOLDER_id val_SUB_FOLDER_id , key1.SUB_FOLDER_NAME key_SUB_FOLDER_NAME,val1.SUB_FOLDER_NAME val_SUB_FOLDER_NAME , key1.disp_name key_disp_name ,key1.dim_id key_dim_id,key1.dim_name key_dim_name,val1.disp_name val_disp_name,val1.dim_id val_dim_id,val1.dim_name val_dim_name ,key1.folder_id key_folder_id ,key1.folder_name key_folder_name,relm.rel_name,relm.is_default FROM  PRG_GRP_DIM_MAP_KEY_VALUE map INNER JOIN PRG_USER_ALL_INFO_DETAILS key1 ON (map.key1       = key1.buss_col_id AND key1.member_id = map.key_mem_id)"
            + " INNER JOIN PRG_USER_ALL_INFO_DETAILS val1 ON ( val1.member_id  = map.mem_mem_id AND val1.buss_col_id = map.value1) LEFT OUTER JOIN prg_grp_dim_rel relm ON (key1.dim_id = relm.dim_id and  relm.is_default ='Y') LEFT OUTER JOIN prg_grp_dim_rel_details reld ON (key1.member_id    = reld.mem_id) where  key1.folder_id    IN (&) AND val1.folder_id IN (&) and key1.BUSS_TABLE_ID = & and val1.BUSS_TABLE_ID = & ORDER BY 1"}, {"insertallDdimMasterDetailsSqlServer", "INSERT INTO PRG_USER_ALL_DDIM_MASTER(INFO_FOLDER_ID,REL_LEVEL,INFO_DIM_ID,INFO_DIM_NAME,INFO_MEMBER_ID, INFO_MEMBER_NAME) SELECT DISTINCT info.folder_id info_folder_id,COALESCE(reld.rel_level,1) rel_level,info.dim_id info_dim_id,info.dim_name info_dim_name,info.member_id info_member_id,info.member_name info_member_name FROM PRG_USER_ALL_INFO_DETAILS info LEFT OUTER JOIN prg_grp_dim_rel relm ON ( info.dim_id    = relm.dim_id AND relm.is_default ='Y' ) "
            + " LEFT OUTER JOIN prg_grp_dim_rel_details reld ON(info.member_id     = reld.mem_id) WHERE info.member_id IS NOT NULL AND info.folder_id    IN (&) and info.BUSS_TABLE_ID = &"}, {"addRoleCustomDrill1", "insert into prg_grp_role_custom_drill(FOLDER_ID,SUB_FOLDER_ID,MEMBER_ID,CHILD_MEMBER_ID,DRILL_ID) values('&',&,'&','&','&')"} //added by Nazneen
        , {"addUserSubFolderElements", "INSERT INTO PRG_USER_SUB_FOLDER_ELEMENTS (ELEMENT_ID, SUB_FOLDER_ID, BUSS_TABLE_ID, BUSS_COL_ID, BUSS_COL_NAME, USER_COL_NAME,"
            + " USER_COL_DESC, USER_COL_TYPE, SUB_FOLDER_TAB_ID,REF_ELEMENT_ID,REF_ELEMENT_TYPE,DEFAULT_AGGREGATION,USE_REPORT_FLAG,Display_Formula) SELECT (PRG_USER_SUB_FLDR_ELEMENTS_SEQ.NEXTVAL) as ELEMENT_ID,"
            + "& as SUB_FOLDER_ID,a.BUSS_TABLE_ID, a.buss_column_id, a.column_name,a.column_disp_name,a.column_display_desc,"
            + "a.column_type,& as SUB_FOLDER_TAB_ID,(PRG_USER_SUB_FLDR_ELEMENTS_SEQ.CURRVAL),1 AS REF_ELEMENT_TYPE,a.default_aggregation,'Y',a.display_formula FROM PRG_GRP_BUSS_TABLE_DETAILS a "
            + "where  a.buss_table_id='&'"}, {"getUserSubFolderElements", "SELECT a.BUSS_TABLE_ID, a.buss_column_id,a.column_name,a.column_disp_name,a.column_display_desc, "
            + " a.column_type ,1 AS REF_ELEMENT_TYPE,a.default_aggregation,a.display_formula FROM PRG_GRP_BUSS_TABLE_DETAILS a "
            + "where  a.buss_table_id='&' "}
//
    };
}
