collection = [
'21ST CEN.MGM',        
'3I INFOTECH',         
'3M INDIA LTD',        
'A.K.CAPITAL',         
'A.SARABHAI',          
'A.V.COTTEX',          
'AADI INDUS L',        
'AAREY DRUGS',         
'AARTI DRUGS',         
'AARTI INDUST',        
'AARVEE DENIM',        
'ABAN OFFSHO',         
'ABB LTD.',            
'ABBOTT (I)',          
'ABC GAS INT',         
'ABC INDIA',           
'ABC PAPER',           
'ABG INFRALOG',        
'ABG SHIPYARD',        
'ABHI CORP LT',        
'ABHINAV CAP',         
'ABHISHEK IND',        
'ABIR NUVONC',         
'ABIRAMI FIN.',        
'ABL BIO-TECH',        
'ABM KNOWLEDG',        
'ACC LTD',             
'ACCEL FRONTL',        
'ACCEL TRANS',         
'ACCENT TECH',         
'ACCURATE TRA',        
'ACE INDIA LT',        
'ACE SOFTWARE',        
'ACI INFOCOM',         
'ACKNIT IND',          
'ACROW INDIA',         
'ACRYCIL LTD.',        
'ACTION CONST',        
'ACTION FIN.',         
'AD-MANUM FIN',        
'ADANI ENTER',         
'ADARSH DERI.',        
'ADARSH PLANT',        
'ADDI IND.',           
'ADF FOODS LT',        
'ADHUNIK MET',         
'ADI BIR NUVO',        
'ADINATH BIO',         
'ADITYA FORGE',        
'ADITYA ISPAT',        
'ADLABS FILMS',        
'ADOR FONTECH',        
'ADOR MULTI.',         
'ADORWELDING',         
'ADVANCE TECH',        
'ADVANCED MIC',        
'ADVANI HOTEL',        
'ADVANTA',             
'ADVENT COMP.',        
'ADVIK LABORS',        
'AEGIS LOGIS',         
'AEKTA LTD.',          
'AEONIAN PUB',         
'AFTEK LTD',           
'AGAR IND COR',        
'AGRO DUTCH I',        
'AGRO TECH FO',        
'AHLCON PAREN',        
'AHLUWALIA CO',        
'AHMED.FORG',          
'AHMED.STEEL',         
'AI CHAMPDNY',         
'AIAENGINEER',         
'AIMCO PESTI.',        
'AISHWARYA TE',        
'AJANTA PHARM',        
'AJANTA SOYA',         
'AJCON GLOBAL',        
'AKANKSHA FIN',        
'AKAR TOOLS L',        
'AKRUTI CITY',         
'AKSH OPTIFIB',        
'AKSHARCHEM I',        
'ALBERT DAVID',        
'ALBR & WILSO',        
'ALCHEMIST LT',        
'ALEMBIC LTD.',        
'ALFA ICA (I)',        
'ALFA LAVAL',          
'ALFA TRANSFO',        
'ALFAVISON.OV',        
'ALFRED HERB',         
'ALKA INDIA',          
'ALKA SECUR.',         
'ALKYL AMINES',        
'ALLAHABAD BK',        
'ALLCARGO GLO',        
'ALLIED COMP',         
'ALLIED DIGIT',        
'ALLSEC TECH',         
'ALMONDZ CMS',         
'ALMONDZ GLO',         
'ALOK INDS.',          
'ALPA LAB',            
'ALPHA HI-TEC',        
'ALPHAGEO (I)',        
'ALPS INDS.',          
'ALSTOM POWER',        
'ALU FLUORIDE',        
'ALUM IND EX',         
'AMAL PRODUCT',        
'AMANI TRAD',          
'AMAR RAJA BA',        
'AMAR REMEDIE',        
'AMARDEEP IND',        
'AMARJOTHI SP',        
'AMBICA AGAR.',        
'AMBIKA COTTO',        
'AMBUJA CEME',         
'AMCO INDIA L',        
'AMD INDUS',           
'AMFORGE IND.',        
'AMINES&PLAST',        
'AMIT INTNL.',         
'AMIT SECUR.',         
'AMIT SPIN.',          
'AML',                 
'AMRAPALI DEV',        
'AMRAPALI IND',        
'AMRAWOR AGRI',        
'AMRIT BANAS',         
'AMRIT BNPS',          
'AMRIT CORP',          
'AMRUTANJ(PS',         
'AMTEK AUTO',          
'AMTEK INDIA',         
'ANAND ELEC.',         
'ANANT RAJ IN',        
'ANCENT SOFT.',        
'ANDHRA BANK',         
'ANDHRA CEMEN',        
'ANDHRA PAPER',        
'ANDHRA PETRO',        
'ANDHRA SUGAR',        
'ANDREW YULE',         
'ANG AUTO',            
'ANIK INDS',           
'ANIL MODI',           
'ANIL PRODUCT',        
'ANIL SP STEL',        
'ANJANI FABRI',        
'ANJANI FINL',         
'ANJANI PORTL',        
'ANJANI SYNT.',        
'ANKIT METAL',         
'ANKUR DRUGS',         
'ANKUSH FINST',        
'ANNA INFRA',          
'ANS AGRO IND',        
'ANSAL BUILD.',        
'ANSAL HOUS.',         
'ANSAL INFRAS',        
'ANTIF BEARNG',        
'ANU LABS',            
'ANUH PHARMA',         
'APAR INDUS.',         
'APCOTEX IND',         
'APEEGO LTD.',         
'APLAB LTD.',          
'APM INDUS.',          
'APOLLO FIN I',        
'APOLLO HOSP.',        
'APOLLO SINDH',        
'APOLLO TYRES',        
'APPLE FINANC',        
'APTECH LTD',          
'APW PRES',            
'ARAVALI SEC.',        
'ARCEE INDUST',        
'ARCHIDPLY IN',        
'ARCHIES LTD',         
'ARCOTECH LTD',        
'AREALTY',             
'AREVA',               
'AREX IND.',           
'ARHAM PLAST.',        
'ARIES AGRO',          
'ARIHANT CAP.',        
'ARIHANT FOUN',        
'ARMAN LEASIN',        
'ARMOUR POLY',         
'ARO GRANITE',         
'ARONI COMM',          
'ARORA FIBRES',        
'ARROW COATED',        
'ARROW WEBTEX',        
'ARSHYIA INTL',        
'ARTEFACT PR',         
'ARTHEON',             
'ARTILLEGENCE',        
'ARTSON ENG',          
'ARVIND CHEM.',        
'ARVIND INTER',        
'ARVIND Ltd',          
'ARVIND MILLS',        
'ARVIND PRODU',        
'ARVIND REM.',         
'ARYAMAN FIN.',        
'ASAHI IN.GLA',        
'ASAHI INFRA.',        
'ASAHI SONG',          
'ASCENT EXIM',         
'ASHAPURA LTD',        
'ASHCO INDS.',         
'ASHIANA AGRO',        
'ASHIANA HOU',         
'ASHIANA ISP.',        
'ASHIM INV',           
'ASHIMA LTD.',         
'ASHIMIN CRP',         
'ASHIRWAD CAP',        
'ASHIRWAD STL',        
'ASHISH POLY.',        
'ASHNOOR TEX.',        
'ASHOK LEYL.',         
'ASIAHR TECH',         
'ASIAN CERC I',        
'ASIAN ELECTR',        
'ASIAN FILMS',         
'ASIAN GRANIT',        
'ASIAN HOTELS',        
'ASIAN I NETW',        
'ASIAN OILFIE',        
'ASIAN PAINTS',        
'ASIAN STAR',          
'ASIAN TEA',           
'ASKME IN HU',         
'ASM TECHNOLO',        
'ASSAM CO.LTD',        
'ASSO.ALCOHOL',        
'ASSOC.STONE',         
'ASTRA MICRO',         
'ASTRAL POLY',         
'ASTRAZEN BON',        
'ASTRAZEN.PH.',        
'ATLANTA',             
'ATLAS COPCO',         
'ATLAS CYCLES',        
'ATN INTER.',          
'ATUL AUTO',           
'ATUL LTD.',           
'AUNDE FAZE T',        
'AURANG.PAPER',        
'AURIONPRO SO',        
'AURO LAB.',           
'AUROB.PHARMA',        
'AUROMA COKE',         
'AUSTIN ENGG.',        
'AUTO AXLES',          
'AUTO COR.GOA',        
'AUTOIND',             
'AUTOLITE(I)',         
'AUTOMOTIVE S',        
'AUTORID.FIN',         
'AVAILABLE FI',        
'AVANTEL SOFT',        
'AVANTI FEEDS',        
'AVAYA GLOBAL',        
'AVENTIS PH.',         
'AVERY INDIA',         
'AVIVA INDS',          
'AVON ORGANIC',        
'AVON WEIGH',          
'AVT NATURAL',         
'AXIS BANK',           
'AXIS CAPITAL',        
'AXIT IT LTD',         
'AXON INFOTEC',        
'AXTEL INDUS.',        
'AZTECSOFT L',         
'B & A LTD.',          
'B.N.RATHI SE',        
'B2B SOFT.',           
'BABA ARTS',           
'BACIL PHARMA',        
'BAFFIN ENG.',         
'BAFNA PHARMA',        
'BAFNA SPG.MI',        
'BAG FIL MED',         
'BAGADIA COLO',        
'BAID LEASING',        
'BAJ HIN SUG',         
'BAJ HOLD INV',        
'BAJAJ AUTO F',        
'BAJAJ AUTO',          
'BAJAJ ELECT.',        
'BAJAJ FINSE',         
'BAJAJ STEEL',         
'BAJAJHIND.LT',        
'BAJAUFINWAR',         
'BAJAUTFINCD',         
'BAL PHARMA',          
'BALA TEC GL',         
'BALA TEC IND',        
'BALAJI AMINE',        
'BALAJI DIST.',        
'BALAJI TELE.',        
'BALARPUR IND',        
'BALASORE',            
'BALKRISH IND',        
'BALMER LA.IN',        
'BALMER LAWRI',        
'BALRAM.CHINI',        
'BALURGHAT TE',        
'BAMBINO AGRO',        
'BAMPSL SECUR',        
'BANCO PROD.',         
'BANG',                
'BANK MAHA',           
'BANK OF RAJ.',        
'BANNARI AMAN',        
'BANNARI AMMA',        
'BANSW.SYNTEX',        
'BARAK VALL',          
'BARTRONICSIN',        
'BASANT AGRO',         
'BASF INDIA',          
'BATA INDIA',          
'BATLIBOI LTD',        
'BAYER CROP',          
'BCC FINANCE',         
'BCC FUBA',            
'BCL FORGING',         
'BDH INDUS.',          
'BECKONSIND',          
'BEEYU OVERSE',        
'BELAPUR IND.',        
'BELL CERAMIC',        
'BELLARY STEE',        
'BEMCO HYDRAU',        
'BEML LTD',            
'BENARES HOT',         
'BENGAL TEA &',        
'BENZO PET.IN',        
'BERGER PAINT',        
'BERYL DRUGS',         
'BEST E.HOTEL',        
'BEST&CROMPT.',        
'BETALA GLOBL',        
'BF UTILI',            
'BGIL FL TEC',         
'BGR ENERGY',          
'BH.IMMUN&BIO',        
'BHAGERIA DYE',        
'BHAGIRA.CHEM',        
'BHAGWANDAS M',        
'BHAGWATI AUT',        
'BHAGWATI BAN',        
'BHAGWATI GAS',        
'BHAGYA INL',          
'BHAGYA.WOOD',         
'BHAGYASHREE',         
'BHANDARI HOS',        
'BHANSALI ENG',        
'BHARAT BHUSH',        
'BHARAT BIJLE',        
'BHARAT ELECT',        
'BHARAT FERTI',        
'BHARAT FORGE',        
'BHARAT GEARS',        
'BHARAT PET.',         
'BHARAT RA(PS',        
'BHARAT SEATS',        
'BHARSHIP',            
'BHARTI ARTL',         
'BHARTIYA INT',        
'BHATINDA CH.',        
'BHEL',                
'BHILWARA SP.',        
'BHOLANATH IN',        
'BHORUKA ALU.',        
'BHURUKA GAS',         
'BHUSH STEEL',         
'BHUWALKA ST.',        
'BIHAR CAUSTC',        
'BIHAR SPONGE',        
'BIHAR TUBES',         
'BILCARE LTD.',        
'BILPOWER LTD',        
'BIMETAL BEAR',        
'BINANI CEM',          
'BINANI IND.',         
'BIO GREEN I',         
'BIOCON LTD.',         
'BIOPAC INDIA',        
'BIRLA CAP',           
'BIRLA CORPN.',        
'BIRLA ERIC.',         
'BIRLA POWER',         
'BIRLA PRETEC',        
'BISLERI GUJ',         
'BITS LTD.',           
'BKV INDUSTRS',        
'BL KASHYAP',          
'BL.CHIP TEX',         
'BLA ROS IND',         
'BLB LTD.',            
'BLISSGVS PH',         
'BLOOM DEKOR',         
'BLUE CHIP(I)',        
'BLUE DART EX',        
'BLUE STAR IN',        
'BLUE STAR',           
'BLUEBIRD(I)',         
'BLUECOASTHL',         
'BNK CAPITAL',         
'BNK OF BA(FI',        
'BNK OF BAROD',        
'BNK OF INDIA',        
'BNR UDYOG',           
'BOC (I) LTD.',        
'BODAL CHEM',          
'BODAL NCPS',          
'BODALCEMWAR',         
'BOM DYEING',          
'BOM.BURMAH',          
'BOM.OXYGEN',          
'BOM.PAINTS',          
'BOM.SWA.STOR',        
'BOMBAY BAROD',        
'BOMBAY RAYON',        
'BONGAIGAON R',        
'BORAX MORARJ',        
'BOROSIL GLAS',        
'BOSCH CHA SY',        
'BOSCH LTD',           
'BPL LTD.',            
'BRABOURNE',           
'BRADY MORRIS',        
'BRAHMANAND',          
'BRAKES AUTO',         
'BRELS INFO.',         
'BRESCON CORP',        
'BRIDGE SECUR',        
'BRIGADE',             
'BRIGHT BROS.',        
'BRIJLAXMI LE',        
'BRILLIANT SE',        
'BRITANIA IND',        
'BROADCAST',           
'BRUSHMAN IND',        
'BSE  INFRA',          
'BSL LTD.',            
'BURNPUR',             
'C & C CONSTR',        
'C.G.IMPEX',           
'C.P.E.C.LTD',         
'CABLE CORP.',         
'CADILA HEALT',        
'CAIRN IND',           
'CALCOM VISIO',        
'CALIFORN.SOF',        
'CALS LTD.',           
'CALS REF LTD',        
'CAM SOLU',            
'CAMBRIDGE',           
'CAMEX LTD',           
'CAMLIN FINE',         
'CAMLIN LTD.',         
'CAMPH.& ALL',         
'CAMSON BIO',          
'CANARA BANK',         
'CANFIN HOMES',        
'CAPITAL TRUS',        
'CAPLIN POINT',        
'CAPMAN FIN.',         
'CAPRIHANS',           
'CARBORUNDUM',         
'CARNATION IN',        
'CARNATION NU',        
'CAROL INFO*',         
'CASTROL',             
'CAT TECHN.',          
'CATVISION PR',        
'CCAP LTD.',           
'CCL PRODUCTS',        
'CCS INFOTECH',        
'CEAT LIMITED',        
'CEEJAY FINAN',        
'CEEKAY DAIK',         
'CELEBRITYFAS',        
'CELEST LABS',         
'CENLUB INDUS',        
'CENTBOP',             
'CENTRAL BK',          
'CENTRAL RLY',         
'CENTRUM CAP',         
'CENTUM ELEC',         
'CENTURY ENKA',        
'CENTURY EXT',         
'CENTURY TEXT',        
'CENTURYPLY',          
'CERA SANITAR',        
'CEREBRA INTE',        
'CESC LTD.',           
'CFL CAPITAL',         
'CG-VAK SOFTW',        
'CHAKKILAM IN',        
'CHAMANLAL SE',        
'CHAMBAL FERT',        
'CHAMPAGNE IN',        
'CHAMPAGNE VI',        
'CHANDNI TEXT',        
'CHANDRA PRAB',        
'CHANDRIKA TR',        
'CHANNEL GUID',        
'CHARMS INDUS',        
'CHARTERED CA',        
'CHARTERLOGIS',        
'CHD DEV LTD',         
'CHEMBOND CHM',        
'CHEMFAB ALK',         
'CHEMPLAST SA',        
'CHENNAI PET.',        
'CHESLIND TEX',        
'CHETTINAD(PS',        
'CHEVIOT CO.',         
'CHI INVEST',          
'CHITRA.SPIN.',        
'CHL LTD',             
'CHOICE INT.',         
'CHOKHANI SEC',        
'CHOKSH INFO.',        
'CHOKSI IMAG',         
'CHOKSI LABOR',        
'CHOLA DBS',           
'CHOLADBSWAR',         
'CHORDIA FOOD',        
'CHOWGULE ST',         
'CIBA INDIA',          
'CIL SECURITS',        
'CINDRELLA FI',        
'CINDRELLA HT',        
'CINEMAX IND',         
'CINERAD COMM',        
'CINEVISTAAS',         
'CIPLA LTD.',          
'CIRCUIT SYS',         
'CITI PORT FN',        
'CITY UNION',          
'CJ GELATIN',          
'CKORAMAA CEM',        
'CLARI CHEM',          
'CLASS.DIAM.',         
'CLAURS',              
'CLIO INFOTEC',        
'CLUTCH.AUTO',         
'CMC LTD.',            
'CMM BROADCAS',        
'CMM HOSPITAL',        
'CNI RES LTD',         
'COASTAL ROAD',        
'COCHIN MIN.',         
'COLGATE PALM',        
'COLINZ LABOR',        
'COMFORT INTE',        
'COMMITMENT C',        
'COMP-U-LEARN',        
'COMPACT DISC',        
'COMPETENT AU',        
'COMPU ////System',        
'COMPUAGE INF',        
'COMPUCOM SOF',        
'COMPUTECH IN',        
'COMPUTER PNT',        
'COMPUTERSKIL',        
'CONART ENG.',         
'CONFI PETRO',         
'CONSOL CONST',        
'CONSOL.SEC.',         
'CONTAIN.CORP',        
'CONTECH SOFT',        
'CONTI.CONTRL',        
'CONTIL I LTD',        
'CONTROL PRNT',        
'CORAL (I)FIN',        
'CORAL LAB.',          
'CORAL NEWSPR',        
'CORDS CABLE',         
'CORE EMBALL.',        
'CORE PROJECT',        
'COROMA.FERT.',        
'CORPN.BANK',          
'COSCO INDIA',         
'COSMO FERR.',         
'COSMO FILMS',         
'COUNTRY CLUB',        
'COUNTRY COND',        
'COVENTRY COI',        
'CRANES SOFTW',        
'CRANEX LTD.',         
'CRAVATEX',            
'CRAZY INFOTE',        
'CREATIVE EYE',        
'CRESSANDA SO',        
'CREST ANIM',          
'CREW BOS',            
'CRISIL LTD',          
'CROMPT.GREAV',        
'CRYSTAL SOFT',        
'CS SOFTWARE',         
'CSS TECH',            
'CUBEX TUBING',        
'CUBICAL FIN.',        
'CUMMINS (I)',         
'CUPID LTD',           
'CUPID TRADE',         
'CYBELE IND',          
'CYBER MEDIA',         
'CYBERMATE',           
'CYBERSCAPE M',        
'CYBERTECH',           
'D&H WELDING',         
'D-LINK INDIA',        
'DAAWAT',              
'DABUR (I)',           
'DABUR PHARMA',        
'DAGGER FROST',        
'DAI-ICHI KAR',        
'DAIKAFFIL CH',        
'DALAL ST INV',        
'DALMIA CEMEN',        
'DAMODAR THR.',        
'DANLAW TECH.',        
'DATAM TECH',          
'DATANET SYS.',        
'DAZZEL CONFI',        
'DB INT.ST.BR',        
'DCM FINANCIA',        
'DCM LTD.',            
'DCM SHR.CON',         
'DCM SHR.IND',         
'DCW LTD.',            
'DECAN CEMENT',        
'DECCAN AVIAT',        
'DECCAN BEAR.',        
'DECCAN CHR',          
'DECCAN POLYP',        
'DECCANGOLD',          
'DECOLIGHT CE',        
'DEEP INDS',           
'DEEPAK FERT.',        
'DEEPAK NITR.',        
'DEEPAK SPINN',        
'DELTON CABLE',        
'DENA BANK',           
'DENISON HYD.',        
'DENSO INDIA',         
'DEPAKNITWAR',         
'DEV CRBANK',          
'DEVINE IMPE',         
'DEVKI LEAS.',         
'DEWAN H.FIN.',        
'DFM FOODS',           
'DGP SECUR.',          
'DHAM SUGAR',          
'DHAMPUR SUGA',        
'DHAMPURE SGR',        
'DHAN AGRI',           
'DHAN JEEVAN',         
'DHAN ROTO SP',        
'DHANALAK.BNK',        
'DHANDAPANI F',        
'DHANLXMI FAB',        
'DHANUSTECH',          
'DHAR TEXTILE',        
'DHARAMSI CHM',        
'DHARANI FIN.',        
'DHARANI SUG',         
'DHOOT I.FIN.',        
'DHP INDIA LT',        
'DHRUV ESTATE',        
'DHRUVA CAP.',         
'DHUNSERI TEA',        
'DIAMINES&CHM',        
'DIAMOND CABL',        
'DIANA TEA CO',        
'DIC INDIA',           
'DIGJAM LTD',          
'DIL LTD',             
'DISA INDIA',          
'DISH TV',             
'DISHMAN PHAR',        
'DIVI'S LAB.',         
'DIVYA.GRANIT',        
'DIVYAJYOTI I',        
'DJS STOCK',           
'DLF LIMITED',         
'DMC INTER',           
'DOLAT INV.',          
'DOLLEX IND.',         
'DOLPHIN MEDI',        
'DOLPHIN OFF.',        
'DONEAR IND.',         
'DOVER SECUR.',        
'DR.AGAR.EYE',         
'DR.REDDY'S',          
'DREDGING COR',        
'DS.KULKARNI',         
'DUJOD PAP CH',        
'DUJODW.PROD.',        
'DUNCANS INDU',        
'DUROFLEX ENG',        
'DUTRON POLY.',        
'DWAR SUGAR',          
'DWS FTS43 IG',        
'DWS FTS43 RD',        
'DWS FTS43 RG',        
'DYNACONS SYS',        
'DYNAMAT.TECH',        
'DYNAMIC IND.',        
'DYNAVISION',          
'DYNEMIC PRO',         
'E.COM INFOTE',        
'E.I.D.PAR',           
'E.STAR INFOT',        
'EAST C.STEEL',        
'EASTER SI(PS',        
'EASTERN GAS',         
'EASUNREYRL',          
'ECE INDUSTRS',        
'ECLERX',              
'ECO BOARD IN',        
'ECOPLAST LTD',        
'EDELWEISS CA',        
'EDUCOMP SOLN',        
'EICHER MOTOR',        
'EIH ASSO.HOT',        
'EIH LTD.',            
'EIMCO ELECON',        
'EL FORGE LTD',        
'ELANGO INDUS',        
'ELANTAS',             
'ELDECO HOUS.',        
'ELDER HEALTH',        
'ELDER PHARMA',        
'ELDER PROJ.',         
'ELEC.CASTING',        
'ELECON ENG',          
'ELECTRA FIN.',        
'ELECTROTHERM',        
'ELEGANT FLOR',        
'ELEGANT MARB',        
'ELGI EQUI PP',        
'ELGI EQUIP',          
'ELGI FINANCE',        
'ELGI TRAD(PS',        
'ELLENBARRIE',         
'ELLORA PAPER',        
'ELNET TECH.',         
'ELPRO INTER',         
'ELTROL LTD.',         
'EMA INDIA',           
'EMAMI LTD.',          
'EMCO LTD.',           
'EMKAY GLOB F',        
'EMKAY SHARE',         
'EMMESSAR BIO',        
'EMMSONS INT.',        
'EMPEE DIST',          
'EMPEE SUGARS',        
'EMPIRE IND.',         
'EMPOWERIND',          
'EMTEX IND.',          
'ENCORE SOFT.',        
'ENERGY DEV.',         
'ENGINRS.(I)',         
'ENGLISH I.CL',        
'ENKEI CASTAL',        
'ENNORCOKWAR',         
'ENNORE COKE',         
'ENRICH IND.',         
'ENSA STEEL',          
'ENT NETWORK',         
'ENTEGRA LTD',         
'ENTERPR.INTE',        
'ENVAIN ELECT',        
'EPC INDUS.',          
'EPIC ENERGY',         
'EPIC ENZYMES',        
'ERA FIN.(I)',         
'ERA INFRA',           
'ESAB INDIA',          
'ESCORT FINAN',        
'ESCORTS LTD.',        
'ESKAY K'N'IT',        
'ESS DEE ALUM',        
'ESSAR OIL',           
'ESSAR SHIP.',         
'ESSEL PROP',          
'ESTER INDUS.',        
'ETC NETWORK',         
'EURO CERAMIC',        
'EURO LEDAR F',        
'EUROTEX IND',         
'EVEREADY (I)',        
'EVEREST INDS',        
'EVEREST KANT',        
'EVERLON SYN.',        
'EVERONN SYS',         
'EVINIX',              
'EXCEL CROP.',         
'EXCEL GLASSS',        
'EXCEL INDUST',        
'EXELON INFRA',        
'EXIDE IND.',          
'EXPO GAS CON',        
'EZ-COMM TRA',         
'FACOR ALLOYS',        
'FACOR STEELS',        
'FACT ENTERP',         
'FAG BEARINGS',        
'FAIRDEAL FIL',        
'FAIRFIELD AT',        
'FALCON TYRES',        
'FAME INDIA L',        
'FAST TRACK E',        
'FAZE THREE L',        
'FCS SOFTWARE',        
'FDC LTD.',            
'FED MOG GOE',         
'FEDDER.LLYOD',        
'FEDERAL BANK',        
'FEM CARE PH.',        
'FENOPLAS.LTD',        
'FERRO ALLOYS',        
'FERT CHE(PS',         
'FGP LTD.',            
'FIBERWB IN',          
'FIEM INDS',           
'FILAT FASH',          
'FILATEX INDI',        
'FILMCITY MED',        
'FIN.EYES(I)',         
'FINANC.TEC.',         
'FINELINE CI',         
'FINOL. CABLE',        
'FINOLEX IND.',        
'FIRST CUSTO.',        
'FIRST LEASIN',        
'FIRST WIN',           
'FLAT PRODUCT',        
'FLAWLESS DIA',        
'FLEX FOODS',          
'FLUIDOMAT',           
'FOMENTO HOTE',        
'FOODS & INNS',        
'FORBES & CO',         
'FORCE MOTR',          
'FORTIS FIN.',         
'FORTIS HEALT',        
'FORTUNE FIN.',        
'FOSECO INDIA',        
'FOUNDRY FUEL',        
'FOUR SOFT',           
'FRESHTROP FR',        
'FRONTIER INF',        
'FRONTIER SPR',        
'FRONTL CORP',         
'FSL',                 
'FULFORD (I)',         
'FUTURA POLY.',        
'FUTURA SEC.',         
'FUTURE CAP',          
'G-TECH INFO.',        
'G.G.DANDEKAR',        
'G.M.BREWERI',         
'G.P.ELECTRON',        
'G.R.CABLES',          
'G.S.AUTO INT',        
'G.T.C.IND.',          
'G.V.FILMS',           
'GABRIEL(I)',          
'GAGAN GASES',         
'GAIL (I) LTD',        
'GAJRA BEVEL',         
'GALADA TELE.',        
'GALAXY ENTER',        
'GALLAN METAL',        
'GAMMA INFOW.',        
'GAMMON INDIA',        
'GAMMON INFRA',        
'GANDHI SP.TU',        
'GANDHI.HOTEL',        
'GANDHIM.APPL',        
'GANESH HSG.',         
'GANESH POLY.',        
'GANESHFORGIN',        
'GANGOTRI IRO',        
'GANGOTRI TEX',        
'GARDEN SILK',         
'GARG FURNACE',        
'GARNET CONST',        
'GARNET INTL',         
'GARWA.MARINE',        
'GARWAR OFF',          
'GARWARE POLY',        
'GARWARE WALL',        
'GATEWAY DIST',        
'GATI LTD.',           
'GAYATRI PROJ',        
'GAYATRI SUGR',        
'GE CAP.TRANS',        
'GEE LTD',             
'GEEFCEE FIN.',        
'GEEKAY FIN.',         
'GEI IND SYS',         
'GEM SPINNERS',        
'GEMINI COMMU',        
'GEMSTONE INV',        
'GENESYS INT.',        
'GENIUS COMMU',        
'GENNEX LAB',          
'GENUS POWER',         
'GEODESIC INF',        
'GEOJIT FIN',          
'GEOMETRIC L',         
'GHCL LTD',            
'GIC HOUSING',         
'GILLA ARBUT',         
'GILLETTE (I)',        
'GINI SILK MI',        
'GINNI FIL(PS',        
'GITANJALI GE',        
'GIVO LTD.',           
'GL HOTELS',           
'GLANCE FIN.',         
'GLAXOSMITH',          
'GLAXOSMITHKL',        
'GLENMARK PHA',        
'GLITTEK GRAN',        
'GLOBAL CAP.',         
'GLOBAL VECT',         
'GLODYNE TECH',        
'GLORY POLY',          
'GLOSTER JUTE',        
'GMM PFAUDLER',        
'GMR FERRO',           
'GMR INDUS LT',        
'GMR INFRASTR',        
'GOA CARBON',          
'GODAVARI DRU',        
'GODAWARI POW',        
'GODFREY PH',          
'GODREJ CONS',         
'GODREJ IND',          
'GOGIA ISEC',          
'GOKAK TEXTI',         
'GOKALDAS',            
'GOKUL REFOIL',        
'GOLDCREST FN',        
'GOLDEN CARPE',        
'GOLDEN LAMIN',        
'GOLDEN SECUR',        
'GOLDIAM INT*',        
'GOLDIAM INT.',        
'GOLDST INFRA',        
'GOLDSTONE EN',        
'GOLECHA GLOB',        
'GOLKUNDA DIA',        
'GOMTI FINLEA',        
'GONTER PEIP',         
'GOOD LUCK ST',        
'GOODRICKE',           
'GOODYEAR (I)',        
'GOPAL IRON S',        
'GOPALA POLY.',        
'GOTHI PLASCO',        
'GOVIND RUBB.',        
'GOWRA LEASNG',        
'GRABAL ALOK',         
'GRANULES (I)',        
'GRAPHITE IN.',        
'GRASIM IND.',         
'GRASIMSL',            
'GRATEX INDS.',        
'GRAUER& WEIL',        
'GRAVITY (I)',         
'GREAT EASTE',         
'GREAT OFFSH',         
'GREAVES COTT',        
'GREENPLY IND',        
'GREMAC INFRA',        
'GREYCELLS EN',        
'GRIFFIN CHEM',        
'GRIND NORTON',        
'GRM OVERSEAS',        
'GRUH FINANCE',        
'GSB FINANCE',         
'GSL SECUR.',          
'GSS AMERICA',         
'GTL INFRAST',         
'GTL LTD.',            
'GTN INDUS',           
'GTN TEXTILE',         
'GUFIC BIO SC',        
'GUJ AMB EXP',         
'GUJ APO IND',         
'GUJ PETRONET',        
'GUJ.ALKALI',          
'GUJ.AUTO GE',         
'GUJ.BOROSIL',         
'GUJ.CARBON',          
'GUJ.CRAFT IN',        
'GUJ.FLOURO',          
'GUJ.FOILS',           
'GUJ.GAS COMP',        
'GUJ.HOTELS',          
'GUJ.IND.POW.',        
'GUJ.INTRUX',          
'GUJ.INVESTA',         
'GUJ.LEASE',           
'GUJ.MINERAL',         
'GUJ.NARMADA',         
'GUJ.NRE COKE',        
'GUJ.PETRO',           
'GUJ.POLY-AVX',        
'GUJ.RECLAIM',         
'GUJ.SIDH.CEM',        
'GUJ.ST.FERT',         
'GUJ.STAT.FIN',        
'GUJ.TERC LAB',        
'GUJ.THEMIS.',         
'GUJ.TOOLROOM',        
'GUJINJK',             
'GULF OIL COR',        
'GULSHAN CHEM',        
'GULSHAN POLY',        
'GULSHAN S&CH',        
'GUPTA SYNTH.',        
'GVK POWERINF',        
'GWALIOR CHEM',        
'H.K.FINECHEM',        
'H.P.COTTON',          
'H.S.(I) LTD.',        
'HALDYN GLASS',        
'HANIL E.TEX',         
'HANJER FIBRE',        
'HANUNG TOYS',         
'HAR.FIBRES',          
'HAR.LEATHER',         
'HARDCASTLE',          
'HARIA EXPORT',        
'HARIG CRANK',         
'HARITA SEAT',         
'HARIYANA SH.',        
'HARR.MALAYAL',        
'HARVCIC MAN.',        
'HARYA CAPFIN',        
'HASTI FINANC',        
'HATHWAY BHAW',        
'HATSUN AGRO',         
'HAVELLSINDIA',        
'HAWKINS COOK',        
'HAZ MUL PRO',         
'HB ESTATE DE',        
'HB LEAS.PUB',         
'HB PORTFOLIO',        
'HB STOCKHOL.',        
'HBL P SYS',           
'HCL INFOSYS',         
'HCL TECHNO',          
'HDFC BANK',           
'HDFC',                
'HEG LTD.',            
'HELIOS & MAT',        
'HENKEL INDIA',        
'HERC.HOISTS',         
'HERITAGE FOO',        
'HERO HONDA',          
'HESTER BISC',         
'HESTER PHARM',        
'HEXAWARE TEC',        
'HFCLINFOTEL',         
'HI-TECH GEAR',        
'HIGH ENERGY',         
'HIKAL LTD.',          
'HILTON MET',          
'HIMACHAL FUT',        
'HIMADRI CHEM',        
'HIMALAYA GR.',        
'HIMALAYA INT',        
'HIMAT.SEIDE',         
'HINAFIL (I)',         
'HIND ALUMIN',         
'HIND UNI LT',         
'HIND.COMPOSI',        
'HIND.CONSTN.',        
'HIND.COPPER',         
'HIND.DORR',           
'HIND.EVEREST',        
'HIND.HARDY',          
'HIND.INDUSTR',        
'HIND.MOTORS',         
'HIND.NAT.GLS',        
'HIND.OIL EXP',        
'HIND.ORG.CHM',        
'HIND.PETRO',          
'HIND.RECT',           
'HIND.SANITAR',        
'HIND.SYNTEX',         
'HIND.TIN WRK',        
'HINDAL PREF',         
'HINDALCO',            
'HINDOO.SPIN.',        
'HINDU.ADHESI',        
'HINDUJA FOUN',        
'HINDUJA VENT',        
'HINDUS.ZI',           
'HINDUSTN BIO',        
'HIPOLIN LTD.',        
'HIRAN ORGOCH',        
'HISAR SPIN.',         
'HISARMET(PS',         
'HITACHI HOME',        
'HITECH PLAST',        
'HITKARI FIB',         
'HITKIT GLOB',         
'HITTCO TOOLS',        
'HMT LTD.',            
'HONDA SIEL',          
'HONEYWELL',           
'HOTEL LEELA.',        
'HOTLINE GLAS',        
'HOTLINE TELE',        
'HOUSING DEV',         
'HOV SERVICES',        
'HOWARD HOTEL',        
'HT MEDIA',            
'HTMT GLOBAL',         
'HULTA PHARMA',        
'HYD.INDUS',           
'HYDERFLEXTC',         
'HYDRO S&S FI',        
'HYTONE TEXST',        
'I-FLEX SOLUT',        
'I-POWER SOLS',        
'I.C.S.A. IND',        
'I.G.PETRO',           
'IB SECURITIE',        
'IBN18',               
'IBRETAILS',           
'ICI INDIA',           
'ICI INDIA*',          
'ICIAPR08TSB1',        
'ICIAPR30TS2',         
'ICICI BANK',          
'ICIRIBSEPT07',        
'ICITX3 JAN02',        
'ICRA',                
'IDBI BANK L',         
'IDEA CELL',           
'IEC SOFT.',           
'IFB AGRO',            
'IFB IND.LTD.',        
'IFCI LTD',            
'IFGL REFRACT',        
'IFL PRMOTER',         
'IFSL LTD.',           
'IGARSHI MOT',         
'IIL',                 
'IKAB SEC.',           
'IKF FINANCE',         
'IKF TECHNO',          
'IL & FS INVE',        
'IL&FS INVTSM',        
'IMPEX',               
'IMPPOWERS',           
'IN HOU PROD',         
'INANI MARBLE',        
'INANI SEC.',          
'INCA FINLEAS',        
'INCAP LTD.',          
'INCON ENGG.',         
'IND CEM CAP',         
'IND INFOLINE',        
'IND-SWIFT LA',        
'IND.ACRYLICS',        
'IND.BANK HSG',        
'IND.BANK MER',        
'IND.CARD',            
'IND.FOILS',           
'IND.GLYCOLS',         
'IND.HUME PIP',        
'IND.LEAS.DEV',        
'IND.SECURITY',        
'IND.SWIFT LT',        
'IND.TONERS',          
'INDAG RUBBER',        
'INDAGIV COMM',        
'INDBUL REAL',         
'INDERGIRI FN',        
'INDHOTELNCD',         
'INDHOTELWAR',         
'INDIA CEM.',          
'INDIA GELAT.',        
'INDIA MOTOR',         
'INDIA NIPPON',        
'INDIA NIVEH',         
'INDIABULLS',          
'INDIACO VEN',         
'INDIAN BANK',         
'INDIAN EXTR.',        
'INDIAN HOTEL',        
'INDIAN OIL',          
'INDIAN OVER.',        
'INDIAN OVERS',        
'INDIAN SUCRO',        
'INDO AMINES',         
'INDO ASI FU',         
'INDO ASN.FIN',        
'INDO BORAX',          
'INDO COUNT',          
'INDO GREEN',          
'INDO RAMA',           
'INDO-CAS.MUL',        
'INDO-CITY IN',        
'INDO-PACIFIC',        
'INDOCO REM',          
'INDOCOUNT FI',        
'INDOKEM LTD.',        
'INDOTECHTR',          
'INDRA GAS',           
'INDRAPRAST',          
'INDRAYANI BI',        
'INDSIL ELSML',        
'INDTRADECO',          
'INDUCTO STL.',        
'INDUS NETWOR',        
'INDUS.&PRUD.',        
'INDUS.INV.TR',        
'INDUSFILA',           
'INDUSIND BNK',        
'INE ABS L',           
'INFO EDGE',           
'INFO-DRIVE S',        
'INFOMEDIA',           
'INFORMEDTEC',         
'INFOSYS TECH',        
'INFOTECH EN.',        
'INFOTREK SYS',        
'INFRA DEVFIN',        
'INFRA INDUS.',        
'ING VYSYA BA',        
'ING VYSYA BN',        
'INGERSOLL',           
'INNOCORP L',          
'INNOVA FOOD',         
'INOX LEISURE',        
'INSILCO LTD.',        
'INT.CONVEYOR',        
'INTEC SEC.',          
'INTEDIGITAL',         
'INTEG.FIN.SE',        
'INTEG.FINANC',        
'INTEG.SWITCH',        
'INTEGR KNIT',         
'INTEGRA CAP.',        
'INTEGRA.HIND',        
'INTEGRA.HITE',        
'INTELVISIONS',        
'INTENS TECH',         
'INTENSIV AIR',        
'INTER DIGI',          
'INTER ST.FIN',        
'INTER ST.OIL',        
'INTER.COMBUS',        
'INTER.TRAVEL',        
'INTERFACE FN',        
'INTERFIT TEC',        
'INTERLINK PE',        
'INTL HOMETEX',        
'INTRA INFOTE',        
'INUSVISTA',           
'INVEST &PREC',        
'INVICTA MED',         
'INWINEX PH',          
'IOL CHEM PH',         
'IOL NET COM',         
'ION EXCHANGE',        
'IP RINGS LTD',        
'IPCA LAB.LTD',        
'IPRUFMP36A D',        
'IPRUFMP36A G',        
'IQ INFOTECH',         
'IQMS SOFT.',          
'IRB INFRA',           
'ISHITA DRUGS',        
'ISHWARSHAKTI',        
'ISMT LTD',            
'ISPAT CRP 10',        
'ISPAT INDS.',         
'ISPAT PR SH',         
'IST LTD.',            
'ISW LTD',             
'IT PEOPLE',           
'ITC LTD.',            
'ITDCEM',              
'ITI LTD.',            
'ITL INDUSTRS',        
'IVP LTD',             
'IVR PRIME',           
'IVRCL INFRAS',        
'IWIND ENERGY',        
'J & K BANK',          
'J KUMAR INFR',        
'J.B.CHEMICAL',        
'J.J.EXPORTER',        
'J.K.AGRI GEN',        
'JAGAN LAMPS',         
'JAGATJIT IND',        
'JAGJANANI',           
'JAGRAN PRAK',         
'JAGSON AIRLI',        
'JAGSON PHAR',         
'JAI CORP LTD',        
'JAIBALA IND',         
'JAIHIND PROJ',        
'JAIN IRRIG',          
'JAIN STUDIOS',        
'JAINCO PROJ.',        
'JAINEX',              
'JAIPAN INDUS',        
'JAIPRA',              
'JAISAL SEC.',         
'JALPAC INDIA',        
'JAMNA AUTO',          
'JAMSHRI RANJ',        
'JANICE TEXT.',        
'JASCH INDUST',        
'JAY HIND SYN',        
'JAY NECO IND',        
'JAY USHIN',           
'JAYANT AGRO',         
'JAYANT MERC.',        
'JAYAVANT PRO',        
'JAYBH.CREDIT',        
'JAYBH.MARUTI',        
'JAYBHARA TEX',        
'JAYPEE HO(PS',        
'JAYSHREE TEA',        
'JAYSHRI CHEM',        
'JAYSN DYEST',         
'JBF IND.LTD',         
'JBM AUTO',            
'JCOP OCCRPS2',        
'JCOP OCCRPS3',        
'JCT ELECTRON',        
'JCT LTD',             
'JD ORGOCHEM',         
'JENBURKT PH.',        
'JENSON &NICH',        
'JETAIRWAYS',          
'JETINFOTRAN',         
'JEYPORESUGAR',        
'JHAGAD COP',          
'JHAV FLEXO',          
'JHAVERI CRED',        
'JHS SVEN',            
'JHUN.VANS.',          
'JIK INDUS.',          
'JINDAL CAP.',         
'JINDAL DRILL',        
'JINDAL HOTL',         
'JINDAL ONLIN',        
'JINDAL PHOTO',        
'JINDAL POLYF',        
'JINDAL SAW',          
'JINDAL SOUTH',        
'JINDAL STAIN',        
'JINDAL STE',          
'JINDAL WORLD',        
'JINDALPH',            
'JJ FINANCE',          
'JK CEMENT',           
'JK LAKSHMI',          
'JK PAPER',            
'JK SUGAR LTD',        
'JK SYNTHETIC',        
'JK TYRE IND',         
'JL MORISON',          
'JM FINANCIAL',        
'JMA INDUS.',          
'JMC PROJECTS',        
'JMT AUTO LTD',        
'JNIL NCCRPS',         
'JOG ENG. LTD',        
'JOINDRE CAPI',        
'JOLLY BOARDS',        
'JOONKTOLLEE',         
'JOSTS ENG.',          
'JP HYDROPOW',         
'JPT SECUR.',          
'JRC INDUS.',          
'JRG SECUR',           
'JSW 10% CRP',         
'JSWSL',               
'JUBILANT ORG',        
'JUMBO BAG',           
'JUPITER BIOS',        
'JYOTHY LAB',          
'JYOTI COSMET',        
'JYOTI LTD.',          
'JYOTI OVER.',         
'JYOTI RESINS',        
'JYOTI STRUCT',        
'K DHANDAPANI',        
'K SERA SERA',         
'K.B.STEEL',           
'K.P.R. MILL',         
'K.S.OILS LTD',        
'KABRA EXTR',          
'KACHCHHMIN',          
'KADAMB CONST',        
'KAILASH AUTO',        
'KAILASH FICO',        
'KAIRA CAN CO',        
'KAJARIA CER.',        
'KAKATIYA CEM',        
'KALE CONSUL.',        
'KALE FILMS',          
'KALINDEE RAI',        
'KALLAM SPG.',         
'KALPA.POWER',         
'KALPANA IND.',        
'KALPTARU',            
'KALYANI FORG',        
'KALYANI STEL',        
'KAMADGIRI SY',        
'KAMAN HSG',           
'KAMAT HOTELS',        
'KAMDHENU',            
'KANANI IND',          
'KANCHAN INT.',        
'KANCO ENTER',         
'KANDAGIRI SP',        
'KANIKA INFO.',        
'KANISHK ST.',         
'KANORIA CHEM',        
'KANPUR PLAST',        
'KANSAI NERO',         
'KAPPAC PHAR.',        
'KAR MOBILES',         
'KARAN WOO-SN',        
'KARNATAKA BK',        
'KARUNA CABLE',        
'KARUR KCP PK',        
'KARUR VY(PS',         
'KARUTURI GLO',        
'KASHYAP TECH',        
'KATARE SPG.',         
'KATWA UDYOG',         
'KAUSHAL INFR',        
'KAVERI SEED',         
'KAVERI TELE',         
'KAY POW PAP',         
'KAY PULP&PAP',        
'KAYCEE IND',          
'KCP LTD',             
'KCP SUGAR IN',        
'KDDL LTD',            
'KDL BIOTECH',         
'KEC INTERN',          
'KEI INDUST.',         
'KELTECH EN.',         
'KEMP & CO.',          
'KEMROCK IND.',        
'KENNAMETAL',          
'KERALA AYUR',         
'KERALA CHEM.',        
'KERNEX MICRO',        
'KESAR ENT.',          
'KESORAM IND',         
'KEW INDUSTR',         
'KEWAL KIRAN',         
'KEYNOTE CORP',        
'KG DENIM',            
'KGN IND LTD',         
'KHAITAN CHEM',        
'KHAITAN ELEC',        
'KHAITAN INDI',        
'KHAITAN WVG',         
'KHANDWALA SE',        
'KHATOR FIBRE',        
'KHOD.INDIA',          
'KHYATI MULTI',        
'KIC METALIKS',        
'KIDUJA INDIA',        
'KILBURN CHEM',        
'KILBURN ENGG',        
'KILBURN OFFI',        
'KILITCH DRUG',        
'KILPEST (I)',         
'KINETIC ENG.',        
'KINETIC MOTO',        
'KINETIC TRUS',        
'KIRAN PRINT',         
'KIRFERROWAR',         
'KIRI DYES',           
'KIRL.BROS.',          
'KIRL.FERROUS',        
'KIRL.OIL ENG',        
'KIRLOSAR PN',         
'KIRLOSKAR EL',        
'KIRTI FINVES',        
'KISAN MOULD.',        
'KITEX GARMEN',        
'KJMC FIN.',           
'KJMC GLOBAL',         
'KLG CAPITAL',         
'KLG SYSTEL',          
'KM SUGARMILL',        
'KNR CONST',           
'KOA TOOL IN',         
'KOFF BR PICT',        
'KOHINOOR BRO',        
'KOHINORFOODS',        
'KOLTEPATIL',          
'KONARK SYN.',         
'KONKAN TYRES',        
'KOPRAN LTD.',         
'KOSIAN INDUS',        
'KOTAK MAH.BK',        
'KOTAK SENSEX',        
'KOTHARI FERM',        
'KOTHARI PROD',        
'KOUTONS RET',         
'KOVAI MEDI.',         
'KOVIL.L.MILL',        
'KPIT INFOSYS',        
'KRBL LTD.',           
'KREBS BIOCHM',        
'KRISH.FILAM.',        
'KRISHNA LIFE',        
'KRITI INDUS.',        
'KRONE COMM',          
'KRYPTON IND',         
'KSB PUMPS',           
'KSE LIMITED',         
'KSK ENERGY',          
'KSL & IND.',          
'KULK-POWER',          
'KUNSTSTOFFE',         
'KUSHAGRA SOF',        
'KUVAM INTL',          
'KWALITY DAIR',        
'KZ LEAS FIN.',        
'L.G.BALKRISH',        
'LA-MERC APP.',        
'LA-OPALA RG',         
'LACTOSE(I)',          
'LADDERUP FIN',        
'LAFFANS PETR',        
'LAHOTI OVER.',        
'LAKHMI COT',          
'LAKSHMI ELEC',        
'LAKSHMI MACH',        
'LAKSHMI MILL',        
'LAKSHMI OVER',        
'LAKSHMI PREC',        
'LAKSHMI VILA',        
'LAMBODHARA T',        
'LANCO GLOBAL',        
'LANCO INDUS.',        
'LANCO INFRA',         
'LANCOR HOLDS',        
'LANDMARC LEI',        
'LANXESS ABS',         
'LARSEN & TOU',        
'LASER DOT',           
'LAWRESHWAR',          
'LEAD FINANC',         
'LEDO TEA CO',         
'LEE&NEE SOFT',        
'LEENA CONS.',         
'LESHA STEELS',        
'LIBERTY PHOS',        
'LIBERTY SHOE',        
'LIBORD INFO.',        
'LIBORDS SEC.',        
'LIC HOUS.FIN',        
'LIFESTYLE FA',        
'LIME CHEM.',          
'LINAKS MICRO',        
'LINC PEN &PL',        
'LINCOLN PHAR',        
'LINEAR POLY',         
'LINK PHARMA',         
'LINKHOUSE IN',        
'LINKSON LEAS',        
'LIPPI ////System',        
'LIVINGROOM L',        
'LKP MER.FIN.',        
'LLOYD ELECT.',        
'LLOYD METAL',         
'LLOYD STEEL',         
'LLOYDS FIN.',         
'LML LTD.',            
'LN POLYESTER',        
'LOGIX MICRO.',        
'LOHIA SECURI',        
'LOK.HOUS&CON',        
'LOKESH MACH',         
'LOTTE I CORP',        
'LOTUS CHOC',          
'LOTUS EYE',           
'LOY.TEX MILL',        
'LUMAX AUTO',          
'LUMAX IND',           
'LUMINAIRE TE',        
'LUPIN LTD.',          
'LYKA LABS',           
'LYNX MACH.',          
'M&M FINANSER',        
'M.B.PARIKH',          
'M.M.FORGINGS',        
'M.M.RUBBER',          
'M.P.AGRO IND',        
'MAARS SOFT.',         
'MAC CHARLES',         
'MACHINO PLAS',        
'MACMILLAN IN',        
'MADAN FIN.',          
'MADHAV MARB.',        
'MADHUCON PRJ',        
'MADHUS.IND.',         
'MADHYA DESH',         
'MADRAS ALUM',         
'MADRAS CEM.',         
'MAESTROS ME',         
'MAFATLAL IND',        
'MAG SHR FIN',         
'MAGNA ELECTR',        
'MAGNUM LTD.',         
'MAGNUM VENT',         
'MAH & MAH',           
'MAH.SCOOTER',         
'MAH.SEAMLESS',        
'MAHA ELEKTRO',        
'MAHA.INDUS.L',        
'MAHA.POLYBUT',        
'MAHA.RUBTECH',        
'MAHA.TELE',           
'MAHAAN FOODS',        
'MAHALAXMI SM',        
'MAHAN IND.',          
'MAHARAJA SHR',        
'MAHASAGAR TR',        
'MAHIN COMP',          
'MAHIND FORG',         
'MAHIND.UGINE',        
'MAHINDRALIFE',        
'MAITHAN ALL',         
'MAJESTIC AUT',        
'MAKERS LAB.',         
'MALAR HOSP.',         
'MALU PAPER',          
'MALWA COTTON',        
'MAN ALUMIN',          
'MAN DRUGORG',         
'MAN IND.(I)',         
'MANAKSIA LTD',        
'MANALI PETRO',        
'MANAPPURAM G',        
'MANGAL VEN',          
'MANGALAM CEM',        
'MANGALAM TIM',        
'MANGALYA SOF',        
'MANGLR.CHEM',         
'MANJUSHREE',          
'MANOJ HSG.FI',        
'MANSI FINANC',        
'MANUGRAPH IN',        
'MARAL OVERS',         
'MARATHON NEX',        
'MARDIA SAMYG',        
'MARG LTD',            
'MARICOLTD',           
'MARKET CREAT',        
'MARKSANS',            
'MARMAGOA ST.',        
'MARSONS',             
'MARTIN BURN',         
'MARUTI INFRA',        
'MARUTI SEC.',         
'MARUTISUZUK',         
'MASCON GLOB.',        
'MASTEK LTD',          
'MASTER TRUST',        
'MATHER & PLA',        
'MATHER & PUM',        
'MATHEW EASOW',        
'MATRIX LABOR',        
'MAVENS BIO',          
'MAWANA SUGAR',        
'MAX INDIA',           
'MAXIMAA SYST',        
'MAXWEL',              
'MAYTAS INFRA',        
'MAYUR LEATHR',        
'MAYUR UNIQ.',         
'MAZDA LTD',           
'MCD HOLDING',         
'MCLEOD RUSSE',        
'MCNALLYB',            
'MCS LTD',             
'MEDI CAPS',           
'MEDIA MATRIX',        
'MEDIA VIDEO',         
'MEDICAMEN BI',        
'MEFCOM AGRO',         
'MEFCOM CAPIT',        
'MEGA CORPN.',         
'MEGASOFT LTD',        
'MEGHMANI',            
'MEHTA I.FIN',         
'MELSTAR INFO',        
'MENON BEAR.',         
'MENON PISTON',        
'MERCATOR LIN',        
'MERCK LTD',           
'METAL COATIN',        
'METALMAN IND',        
'METROCHE.IND',        
'MEWAR INDUS.',        
'MEWAR POLYTX',        
'MH MILLS IND',        
'MIC ELECTRON',        
'MICRO FORGE',         
'MICRO INKS L',        
'MICRO TECHO',         
'MID EAST POR',        
'MID INDIA IN',        
'MID-DAY MULT',        
'MIDAS PHARMA',        
'MILKFOOD',            
'MILLEN.CYBER',        
'MILLENNIUM B',        
'MILTON PLAST',        
'MINAL ENGG.',         
'MINAXI TEXT.',        
'MINDA IND',           
'MINDTECK (I)',        
'MINDTREE LTD',        
'MINERAL&METL',        
'MINI DIAMOND',        
'MIRC ELECT',          
'MIRZA INTER',         
'MK EXIM',             
'MOBILE TELE',         
'MODELLA WOOL',        
'MODERN DAIRI',        
'MODERN INDIA',        
'MODERN SHARE',        
'MODERN STEEL',        
'MODIPON',             
'MODISON MET.',        
'MOHIT INDUS.',        
'MOHIT PAPER',         
'MOLD-TEK TEC',        
'MONET SUGAR',         
'MONNET IND.',         
'MONNET ISPAT',        
'MONOZYME (I)',        
'MONSANTO (I)',        
'MORARJETEX',          
'MORARKA FIN.',        
'MOREPEN LAB.',        
'MORGAN CRU',          
'MORGAN IND',          
'MORGAN STANL',        
'MORGAN VENT',         
'MORTEXTWARR',         
'MOSCHIP SEMI',        
'MOSER BEAR',          
'MOTHERSON SS',        
'MOTILALOFS',          
'MOTOR&GEN.FI',        
'MOUNT EVERES',        
'MOUNT TRAD',          
'MOUNTT SHIV.',        
'MOVING PI(PS',        
'MPHASIS LTD',         
'MPIL CORP L',         
'MRF LTD.',            
'MRO-TEK LTD',         
'MRPL',                
'MSK PROJECTS',        
'MSP STEEL',           
'MTZ POLYFILM',        
'MUDRA',               
'MUKAND ENGG.',        
'MUKAND LTD.',         
'MUKAT PIPES',         
'MUKESH BABU',         
'MUKESH STEEL',        
'MUKESH STRIP',        
'MUKTA ARTS',          
'MUKUND CRPS',         
'MUKUNDA IND.',        
'MULLER & PHI',        
'MULTI ARC',           
'MULTIBASE I',         
'MUNAUTO',             
'MUNDRA PORT',         
'MUNJAL SHOWA',        
'MUNOTH FIN.',         
'MUNOTH INVES',        
'MURD.CERAM',          
'MURLI INDU',          
'MUTHOOT CAP',         
'MVL LIMITED',         
'MY FAIR LADY',        
'MYS CEMENTS',         
'MYS PETRO',           
'MYSORE PAPER',        
'N C L IND.',          
'N K INDUST.',         
'N.D.METAL',           
'N.G.IND.LTD.',        
'N.R.AGARWAL',         
'NABARD2I2',           
'NACHMO KNITX',        
'NAGAR.AGRICH',        
'NAGAR.AGRITE',        
'NAGAR.CONST.',        
'NAGARJ.FERT.',        
'NAGPUR POWER',        
'NAGREEKA EXP',        
'NAGREKA CAP',         
'NAHAR CAP',           
'NAHAR INDUST',        
'NAHAR INVEST',        
'NAHAR SPG.',          
'NAKODA TEXT',         
'NALIN LEASE',         
'NALWA SONS',          
'NANDAN EXIM',         
'NARENDRA PRO',        
'NARMADA GEL',         
'NAT STL AGRO',        
'NAT.ALUM',            
'NAT.PEROXIDE',        
'NAT.PLASTIC',         
'NATCO PHARM',         
'NATH PULP',           
'NATI. OXYGEN',        
'NATIONAL FER',        
'NATIONAL GEN',        
'NATRAJ FIN',          
'NATRAJ PROTE',        
'NATURA HUE C',        
'NATURAL CAPS',        
'NAV BHAR VEN',        
'NAVIN FLUORI',        
'NAVKAR BUILD',        
'NAVNEET PUBL',        
'NCC FINANCE',         
'NCJ INTERNAT',        
'NDA SECURIT.',        
'NDTV',                
'NECTAR LIFE',         
'NEELKANTH RO',        
'NEELKANTH TE',        
'NEEMTEK ORG',         
'NEENA CONSUL',        
'NEHA INTER.',         
'NELCAST',             
'NELCO LTD.',          
'NEOCORP INTE',        
'NEOGEM INDIA',        
'NEPC INDIA',          
'NESCO LTD',           
'NESTLE (I)',          
'NET 4 INDIA',         
'NETFL FINCO',         
'NETLINK SOLU',        
'NETTLINX LTD',        
'NETVIS',              
'NETVISTA INF',        
'NETW18PCCPS',         
'NETWORK LTD.',        
'NETWORTH STK',        
'NEULAND LAB.',        
'NEXXOFT INFO',        
'NEYVELI LIGN',        
'NGL FINE CHM',        
'NICCO COR(PS',        
'NICCO PARKS',         
'NICCO UCO AL',        
'NICHOLAS PIR',        
'NIDHI GRANIT',        
'NIHAR INFO',          
'NIIT LTD.',           
'NIITTECH',            
'NIKHIL ADHSV',        
'NIKKI GLOBAL',        
'NILA INFRA.',         
'NILE LTD.',           
'NILKAMAL L',          
'NIPPO BATT',          
'NIRAJ CEMENT',        
'NIRAV COMMER',        
'NIRLON',              
'NIRMA LTD',           
'NIRYAT SAM A',        
'NISSAN COPER',        
'NITCO TILES',         
'NITIN ALLOY',         
'NITIN FIRE',          
'NITINSPINNER',        
'NIYATI IND..',        
'NMDC LTD',            
'NOBLE EXPLO.',        
'NOCIL LTD',           
'NOIDA MEDI',          
'NOIDA-TOLL B',        
'NORTHGATE TE',        
'NOUVEAU MUL.',        
'NOVA PETRO.',         
'NOVAGOL PETR',        
'NOVAPAN IND.',        
'NOVARTIS',            
'NPR FINANCE',         
'NR INTERNA',          
'NRB BEARINGS',        
'NRC LTD.',            
'NTPC LTD',            
'NTWK MED INV',        
'NU-TECH CORP',        
'NUC NET GIS',         
'NUCENT FIN.',         
'NUCHEM LTD.',         
'NUCLE.SOFT E',        
'NUMERIC POWE',        
'NUTRAPLUS PR',        
'OASIS SECUR.',        
'OBCSL',               
'OCEAN AGRO',          
'OCEAN INFRA.',        
'OCL INDIA',           
'ODYSSEY CORP',        
'ODYSSEY TECH',        
'OIL COUNTRY',         
'OK PLAY (I)',         
'OM MET INFRA',        
'OMAX AUTOS.',         
'OMAXE LTD',           
'OMEGA INTERA',        
'OMNI AX'S SO',        
'OMNITECH',            
'OMNITEX IND.',        
'ONGC CORPN',          
'ONMOBILE',            
'ONTRACK',             
'ONWARD TECHN',        
'OPTO CIRCUIT',        
'ORBIT EXPORT',        
'ORBIT WAR',           
'ORBITCO',             
'ORCHID CHEM',         
'ORG INFORMAT',        
'ORGANIC COAT',        
'ORICON ENT',          
'ORIENT ABRAS',        
'ORIENT BEVER',        
'ORIENT CERAM',        
'ORIENT HOTEL',        
'ORIENT INFO.',        
'ORIENT PAPER',        
'ORIENT PRESS',        
'ORIENT.CARB.',        
'ORIENTAL VEN',        
'ORIENTAL',            
'ORIND EXPORT',        
'ORINTAL BANK',        
'ORION PAPER',         
'ORISA SP IRS',        
'ORTIN LABS',          
'OSCAR GLOBAL',        
'OSCAR INV.',          
'OSWAL SPG(P)',        
'OSWAL YARNS',         
'OUDH SUGAR',          
'OXFORD INDUS',        
'P.G.FOILS',           
'P.H.CAPITAL',         
'PACE TEXTILE',        
'PACIFIC COTS',        
'PADAM COTTON',        
'PADMALAYA TE',        
'PAGE INDUSTR',        
'PAL CREDIT',          
'PAN ELECTR.',         
'PAN INDIA C',         
'PANACEA BIOT',        
'PANAMA PETRO',        
'PANASON BAT',         
'PANASON CAR',         
'PANASON HOME',        
'PANCH.STEEL',         
'PANCHSHEEL O',        
'PANKAJ POLY.',        
'PANORAM UNI',         
'PANTALOON RE',        
'PANYAM CEMEN',        
'PAPER PROD',          
'PARAAN LTD.',         
'PARAGON FIN.',        
'PARAL',               
'PARAMOUNT CO',        
'PARAS PETRO',         
'PAREKH PLATI',        
'PARENT.DRUGS',        
'PARKER AGRO.',        
'PARLE SOFTWR',        
'PARSHARTI IN',        
'PARSOLI CORP',        
'PARSVNATH',           
'PAS.ACRYLON',         
'PASARI SPIN',         
'PASSARI CELL',        
'PAT INT LOG',         
'PATEL AIRTEM',        
'PATEL ENGG.',         
'PATNI COMP',          
'PATSPIN INDI',        
'PAUSHAK LTD',         
'PBA INFRASTR',        
'PBM POLYTEX',         
'PCS TECH',            
'PEACOCK IND.',        
'PEARL ENG.PO',        
'PEARL FASHON',        
'PEARL GLOBAL',        
'PEARL POLYME',        
'PEE CEE COSM',        
'PENLAND LTD',         
'PENN IND PS',         
'PENNAR ALUM.',        
'PENNAR STEEL',        
'PENTAMED.G',          
'PENTASOFT TE',        
'PERFECTPAC',          
'PERM MAGNETS',        
'PETRON ENGG.',        
'PETRONET LNG',        
'PFIZER LTD.',         
'PFL INFOTECH',        
'PHARMAIDS PH',        
'PHARMASIA',           
'PHIL.CARBON',         
'PHOENIX INT.',        
'PHOENIX LAMP',        
'PHOENIX MILL',        
'PHOTOQUIP(I)',        
'PHYTOCHEM I.',        
'PI INDUS.LTD',        
'PICCADILY AG',        
'PICCADILY SU',        
'PIDILITE',            
'PION INVEST',         
'PIONEER AGRO',        
'PIONEER DIS.',        
'PIONEER EMB',         
'PIRAM LIFE',          
'PIRAMA HEALT',        
'PIRAMAL GLAS',        
'PIRAMYD RETL',        
'PITTI LAMIN.',        
'PIX TRANS',           
'PLASTIBLEND',         
'PLATI CORP',          
'PLETHICO',            
'PNB GILTS',           
'PNBSL',               
'POCHIRAJU IN',        
'PODDAR PIGM.',        
'POKARNA LTD',         
'POLAR INDUS.',        
'POLAR PHARMA',        
'POLARIS SOFT',        
'POLO HOTELS',         
'POLY MEDICUR',        
'POLYCHEM',            
'POLYCON INT.',        
'POLYGENTA TE',        
'POLYLINK POL',        
'POLYMECH.MCH',        
'POLYPLEX',            
'POLYSPIN EXP',        
'PONDY OXIDES',        
'PONNI SUG(ER',        
'POONA DAL',           
'POONAM CORPN',        
'PORWAL AUTO',         
'POWER FINAN',         
'POWER GRID',          
'POWERSOFT',           
'PRADEEP MET.',        
'PRAG BOSIMI',         
'PRAJ IND.LTD',        
'PRAJAY ENGS.',        
'PRAKASH IND.',        
'PRATIBHA IND',        
'PRATIK PANEL',        
'PRATIKSHA CH',        
'PRECI CONTNR',        
'PRECISION EL',        
'PRECISION WR',        
'PRECISION',           
'PREM.AU.ELEC',        
'PREMCO GLOB.',        
'PREMIER EXPL',        
'PREMIER LTD',         
'PREMIUM CAP',         
'PRERNA INFR',         
'PRESSURE SEN',        
'PRI.SPINNING',        
'PRICOL LTD.',         
'PRIMA PLASTI',        
'PRIME FOCUS',         
'PRIME INDS.',         
'PRIME PROP',          
'PRIME SECUR.',        
'PRIME TEXTIL',        
'PRISM CEMENT',        
'PRITHVI INFO',        
'PRITISHN COM',        
'PRIYA LTD.',          
'PRO DEV&TEC',         
'PROCAL ELECT',        
'PROCTER &GAM',        
'PROMACT PLAS',        
'PROVOGUE IND',        
'PRRANETA IND',        
'PSI DATA SYS',        
'PSL LTD',             
'PTC INDIA',           
'PTL LTD',             
'PUDMJEE IND',         
'PUDUMJEE',            
'PUN.ALKALI',          
'PUN.CHEM',            
'PUN.COMMUNI.',        
'PUN.WOOLCOMB',        
'PUNEET RESIN',        
'PUNJ LLOYD',          
'PUNJAB NATIO',        
'PUNJAB TRACT',        
'PURAVANKARA',         
'PVP VENT LTD',        
'PVR LTD',             
'PYRAMID SAIM',        
'QUINTEGRA SO',        
'R R FINANCE.',        
'R.A.S.EXTRU',         
'R.J.SHAH',            
'R.M.MOHITEX',         
'R.S.SOFTWARE',        
'R.T.EXPORTS',         
'RAASI REFRAC',        
'RADAAN MEDIA',        
'RADHA MADHAV',        
'RADHE DEVLOP',        
'RADICOKHAIT',         
'RAGHAV IND.',         
'RAGHUNATH IN',        
'RAGHUNATH TO',        
'RAINBOW FOUN',        
'RAINBOW PAP.',        
'RAINCOMMODI',         
'RAISAHEB RCK',        
'RAJ AGRO MIL',        
'RAJ GLO WIR',         
'RAJ PACKAGIN',        
'RAJ RAYON',           
'RAJ TELE',            
'RAJ.TUBE MFG',        
'RAJAPAMILLS',         
'RAJDARSHAN',          
'RAJEN.MECH.',         
'RAJES FOUND',         
'RAJESH EXPO.',        
'RAJKUMAR FRG',        
'RAJOO ENGIN.',        
'RAJSH.SUGAR',         
'RAJVIR IND',          
'RALLIS INDIA',        
'RAM INFORMAT',        
'RAM KAASHYAP',        
'RAM RAT.WIRE',        
'RAMA NEWSPRI',        
'RAMA PAPER',          
'RAMA PETRO',          
'RAMA PHOSPH',         
'RAMA PULP',           
'RAMA VISION',         
'RAMCO  SYSTM',        
'RAMCO INDS.',         
'RAMMAICA (I)',        
'RAMSARUP IND',        
'RAMSONS PROJ',        
'RANA SUGARS',         
'RANBAXY LAB.',        
'RANDER CORP.',        
'RANE BRAKE',          
'RANE ENGVL',          
'RANE HOLDIN',         
'RANE MADRAS',         
'RANKLIN SOLU',        
'RAP MEDIA',           
'RAPICUT CARB',        
'RAS PROPACK',         
'RAS RESORTS',         
'RASANDIK ENG',        
'RASHEL AGRO.',        
'RASHTR.CHEM.',        
'RASI ELECTRO',        
'RASOI LTD.',          
'RASOYA PROTE',        
'RATHI BARS',          
'RATHI GRAPH.',        
'RATHI ISPAT',         
'RATHI UDYOG',         
'RATNABALI CA',        
'RATNAMNI MET',        
'RAUNAQ AUTO',         
'RAVALGAON',           
'RAVINAY TRAD',        
'RAYBAN SUN',          
'RAYMOND',             
'RDB INDUSTRI',        
'REAL STRIPS',         
'RECLTD',              
'REDINGTON',           
'REFEX REFRIG',        
'REFNOL RESIN',        
'REG.CERAMIC',         
'REGA REALTY',         
'REGAL ENTERT',        
'REI AGRO LTD',        
'REL COM LTD',         
'REL INDL INF',        
'REL INFRA',           
'REL PET',             
'REL.CAP.',            
'REL.CHEMOTX',         
'RELAXO FOOT.',        
'RELIAB VEN',          
'RELIANCE',            
'RELIC TECHNO',        
'RELIGARE ENT',        
'REMI METALS',         
'REMSONS IND.',        
'REN JEWELERY',        
'RENUKA SUGAR',        
'REPRO INDIA',         
'RESPON IND',          
'RESTILE CER.',        
'REVATHI EQU.',        
'REXNORD ELE.',        
'RFL INTERNAT',        
'RIBA TEXTILS',        
'RICH CAPITAL',        
'RICHA KNITS',         
'RICHIRICH AG',        
'RICO AUTO',           
'RICOH INDIA',         
'RIDHI SIDHI',         
'RIDS SECUR.',         
'RIGA SUGAR',          
'RIL NAT RES',         
'RISHABH DIGH',        
'RISHI LASER',         
'RISHI PACKER',        
'RISHIROOP RU',        
'RIT PRO IND',         
'RITESH INTER',        
'RJL WAR 1JUN',        
'RK FORGINGS',         
'RLF LIMITED.',        
'RNBOWDENIM',          
'ROBINSON WOR',        
'ROCK.H.PETRO',        
'ROHIT FERRO',         
'ROHIT PULP',          
'ROLLATAINER',         
'ROLTA (I)',           
'ROMAN TAR',           
'ROOPA INDUS',         
'ROSE LABS.',          
'ROSE ZINC',           
'ROSELABS FIN',        
'ROTAM COMM.',         
'ROTO PUMPS',          
'ROYAL CUSHIO',        
'ROYALE MANOR',        
'ROYALORCH',           
'RPG CABLES',          
'RPG LIFESCI',         
'RPOWER',              
'RSWM  LTD',           
'R////SystemS INT',        
'RTS POWER CO',        
'RUBBER PROD.',        
'RUBFILA INT.',        
'RUBY MILLS',          
'RUCHI INFRA.',        
'RUCHI SOYA',          
'RUCHI STRIPS',        
'RUCHIRA PAP',         
'RUNGTA IRRIG',        
'RUTTONSHA IN',        
'S KUMARS.COM',        
'S.A.ENTERPR.',        
'S.B.& T INT.',        
'S.I.PAPER',           
'S.KUMARS NAT',        
'S.R.INDUS.',          
'S.S.DUNCAN',          
'S.S.ORGANICS',        
'SAAG RR INFR',        
'SAAMYA BIO',          
'SAARC NET LT',        
'SABERO ORG.',         
'SABOO SODIUM',        
'SACHETA MET.',        
'SADBHAV ENGG',        
'SADHANA NITR',        
'SAFARI IND.',         
'SAGAR CEM.',          
'SAGAR T.RES.',        
'SAHARA HOUSG',        
'SAHARA ONE',          
'SAHIL FINANC',        
'SAHPETROLEUM',        
'SAHYA INDU',          
'SAI SERVICES',        
'SAINIK FIN.',         
'SAINT-GOBAIN',        
'SAKSOFT LTD',         
'SAKTHI FIN.',         
'SAKTHI SUGAR',        
'SAKUMA EXPO',         
'SALONA COTSP',        
'SALORA INT.',         
'SALSTEEL',            
'SALZER ELEC',         
'SAM INDUS.',          
'SAMBANDAM SP',        
'SAMBHAAV MED',        
'SAMKRG PIST.',        
'SAMRAT PHARM',        
'SAMTEL COL',          
'SAMTEL IND.',         
'SAMTEX FASH.',        
'SANCO TRANS',         
'SANDESH LTD.',        
'SANDU PHARMA',        
'SANDUR MANG.',        
'SANGAM INDIA',        
'SANGHI IND.',         
'SANGHVI MOVE',        
'SANGUINE MD',         
'SANJAY LEAS',         
'SANJIVANI PA',        
'SANKET INTR.',        
'SANKHYA INFO',        
'SANRA COMP.',         
'SANTARAM SPN',        
'SANTOGEN EXP',        
'SANTOSH FINE',        
'SANWARIA AGR',        
'SAR SAROVR-D',        
'SARANG CHEM.',        
'SARDA ENMIN',         
'SARDA PAPERS',        
'SARDA PLY.',          
'SAREGAMA (I)',        
'SARLA PER F',         
'SARUP TANNER',        
'SASKEN COMM',         
'SAT IND LTD',         
'SATPROP LTD',         
'SATVAH.ISPAT',        
'SATYAM COM',          
'SAURAS.CEM.',         
'SAV INFOCOM',         
'SAVANI FIN.',         
'SAVEN TECHNO',        
'SAVERA IND',          
'SAVITA CHEM.',        
'SAYA HSG.FIN',        
'SAYAJI HOTEL',        
'SBEC SUGAR',          
'SCANA COLOUR',        
'SCANPOINT GR',        
'SCENARIO MED',        
'SCHABLONA (I',        
'SCHLAF.ENGG.',        
'SCINDIA STEA',        
'SCOOTERS IND',        
'SE INVESTM',          
'SEAMEC LTD',          
'SEASONS FUR.',        
'SEASONS TEXT',        
'SEAX GLOBAL',         
'SECUND.HEALT',        
'SECURIT.CAP',         
'SEJAL GLASS',         
'SEL CRPS',            
'SEL MANUF',           
'SELAN EXPLOR',        
'SELLAIDS PUB',        
'SER INDUST.',         
'SESA GOA',            
'SESHA.PAPER',         
'SESHACHAL',           
'SETCO AUTO',          
'SGN TELECOMS',        
'SH.BHAWANI',          
'SH.HARI CHEM',        
'SH.PACETRON.',        
'SH.PRECOATED',        
'SH.STEEL WIR',        
'SH.VANI SUGR',        
'SHAH ALLOYS',         
'SHAH FOOD(P)',        
'SHAKTI MET-D',        
'SHAKTI PUMPS',        
'SHALIB.FINAN',        
'SHALIMAR PAI',        
'SHALIMAR PRO',        
'SHALIMAR WIR',        
'SHAMKEN COT.',        
'SHAMKEN MULT',        
'SHAMKEN SPIN',        
'SHAMROCK IND',        
'SHANTHI GEAR',        
'SHANTIVIJAY',         
'SHARDUL SECU',        
'SHARON BIO',          
'SHARP INDIA',         
'SHARYANS RES',        
'SHASUN CHEM.',        
'SHAW WALLACE',        
'SHEETAL BIO',         
'SHERVANI IND',        
'SHETRON LTD',         
'SHILCHAR TEC',        
'SHILP GRAVUR',        
'SHILPA MEDIC',        
'SHIMOGA TECH',        
'SHIPP.CORPN',         
'SHIRPUR GOLD',        
'SHIV.BIMETAL',        
'SHIVA CEMENT',        
'SHIVA FERT.',         
'SHIVA TEXYAM',        
'SHIVAM AUTO',         
'SHIVVANI OIL',        
'SHLOKA INFO',         
'SHOPPER STOP',        
'SHRE AJIT PU',        
'SHREE ASHTA',         
'SHREE CEMENT',        
'SHREE GLOBAL',        
'SHREE KRISHN',        
'SHREE RAJSYN',        
'SHREE RAM',           
'SHREE RAMA',          
'SHREENATH',           
'SHRENUJ & CO',        
'SHREY SH LOG',        
'SHREYANS IND',        
'SHREYAS INTE',        
'SHRI BAJRANG',        
'SHRI DINESH',         
'SHRICON IND.',        
'SHRIRAM ASSE',        
'SHRIRAM EPC',         
'SHRIRAM TRAN',        
'SHRISTINFRA',         
'SHRMCITYUN',          
'SHUKRA JEW',          
'SHUKUN CONS.',        
'SHYAM SOFT.',         
'SHYAM STAR G',        
'SHYAM TELEC.',        
'SHYAMLAL HOL',        
'SI GROUP',            
'SICAL LOG',           
'SIDDHA VEN',          
'SIDDHARTH TB',        
'SIEMENS LTD.',        
'SIEMENS MED',         
'SIKA INTER.',         
'SIL INVEST',          
'SILICON VAL.',        
'SILKTEX LTD.',        
'SILVER ANIMA',        
'SILVER SMITH',        
'SILVERLINE',          
'SIMBH.SUGAR',         
'SIMMONDS-MAR',        
'SIMPLEX CAST',        
'SIMPLEX PROJ',        
'SIMPLEX REAL',        
'SIMPLEX TRAD',        
'SIMPLX INFRA',        
'SIMRAN FARMS',        
'SINCLAIR HOT',        
'SINGER INDIA',        
'SINNAR BIDI',         
'SINTEX IND.',         
'SIP INDUST.',         
'SIR SHADI LA',        
'SIRPUR PAPER',        
'SITA ENTER.',         
'SITA SHREE',          
'SIYARAM SILK',        
'SJ CORP LTD',         
'SKF INDIA',           
'SKM EGG PROD',        
'SKP SECURE.',         
'SKS LOG LTD',         
'SKY INDUST.',         
'SKYL MILLAR',         
'SKYPAK SERV.',        
'SM ENERGY',           
'SMIFS CAPITA',        
'SMRUTHI ORG',         
'SMS PHARMACE',        
'SNL BEARINGS',        
'SNS TEXTILES',        
'SOBHA DEV',           
'SOFTBPO GLOB',        
'SOFTPRO SYS.',        
'SOFTSOL (I)',         
'SOFTWARE TEC',        
'SOLAR EXPL',          
'SOLECT EMS',          
'SOLID STONE',         
'SOLITAIR MAC',        
'SOLIX TECHNO',        
'SOLVAY PHAR.',        
'SOM DISTILL.',        
'SOMA TEXTILE',        
'SOMANY CRAM',         
'SOMDATT FIN',         
'SOMI CONVEY',         
'SONA KOYO ST',        
'SONATA SOFT.',        
'SOUTH ASIA P',        
'SOUTH IND.BK',        
'SOUTH PET(PS',        
'SOUTH.ISPAT',         
'SOUTHBIOTEC',         
'SOVEREIGN DI',        
'SOWBH MEDIA',         
'SP CAPITAL',          
'SPAN DIAGNOS',        
'SPANCO TELE.',        
'SPARSH BPO',          
'SPECIALITY P',        
'SPECTRA IND.',        
'SPEL SEMICON',        
'SPENTA INT.',         
'SPENTEX INDS',        
'SPICE ISLAND',        
'SPICE MOBIL',         
'SPICE TELE',          
'SPICE-ETF',           
'SPICEJET LTD',        
'SPL INDS',            
'SPL POLYMER',         
'SPLASH MEDIA',        
'SPS INTL.',           
'SQL STAR INT',        
'SREE RAYALA',         
'SREE SAKTHI',         
'SREE.RAY.ALK',        
'SREIINFRA',           
'SRF LIMITED',         
'SRF LIMITED*',        
'SRF POLYMER',         
'SRHHL IND',           
'SRI ADHIKARI',        
'SRI DIGV CEM',        
'SRI GANAPATH',        
'SRI JAYALAKS',        
'SRI LAK.SAR.',        
'SRI NACHAMAI',        
'SRI RAMK.MIL',        
'SRINIVASA HA',        
'SRINIWAS SHP',        
'SRIVEN MULT.',        
'SRRAYL ALKPS',        
'SS FORG ENG.',        
'SSI LTD.',            
'ST.BANK BIKA',        
'ST.STR.WHEEL',        
'STANPACKS(I)',        
'STANROSE MAF',        
'STAR PAPER',          
'STATE BANK',          
'STATE BANK(R',        
'STATE BNK MY',        
'STATE BNK TR',        
'STC INDIA',           
'STD.INDUST.',         
'STEEL AUTH.',         
'STEEL EXCH',          
'STEELCAST',           
'STEELCO GUJ.',        
'STEL.STR.&TU',        
'STELCO STRIP',        
'STER TECH',           
'STERL INTER',         
'STERL.BIOTEC',        
'STERL.HOL.RS',        
'STERL.TOOLS',         
'STERLITE IN',         
'STEWARTS',            
'STI INDIA LT',        
'STL GLOBAL',          
'STOCK NET IN',        
'STONE INDIA',         
'STOVAC IND.',         
'STR GRE WOO',         
'STRESSCRETE',         
'STRIDES',             
'STURDY INDS',         
'SU-RAJ DIAM.',        
'SUASHISH DIA',        
'SUAVE HOTEL',         
'SUBEX LTX',           
'SUBHASH PROJ',        
'SUBHKAM CAP',         
'SUBROS LTD.',         
'SUBUTHI FIN.',        
'SUDAL INDUS',         
'SUDARSH.CHEM',        
'SUDITI IND.',         
'SUGAL DAMANI',        
'SUJANA INDUS',        
'SUJANA METAL',        
'SUJANATOWER',         
'SUKJIT STRCH',        
'SULZER(IND)',         
'SUMEDHA FISC',        
'SUMEET INDS.',        
'SUMERU IND',          
'SUMMIT SEC',          
'SUN PHARMA.',         
'SUN TVNET',           
'SUNCITY SYNT',        
'SUNDAR.CLAY',         
'SUNDARAM BRK',        
'SUNDARAM FAS',        
'SUNDARAM FIN',        
'SUNDARAM',            
'SUNFLAG IRON',        
'SUNGOLD CAP.',        
'SUNIL AGRO F',        
'SUNIL HITECH',        
'SUNITEE CHEM',        
'SUNPHA ADV',          
'SUNRAJ DIAM.',        
'SUNSHIELD CH',        
'SUNTECK REAL',        
'SUPER BAKERS',        
'SUPER CROP.',         
'SUPER HOUSE',         
'SUPER SAL IN',        
'SUPER SPIN.',         
'SUPER SYNCOT',        
'SUPER TANNER',        
'SUPERTEX IND',        
'SUPRAJIT ENG',        
'SUPREME HOLD',        
'SUPREME IND.',        
'SUPREME INFR',        
'SUPREME PETR',        
'SUPREME TEX',         
'SURAJ STAINL',        
'SURANA CORPO',        
'SURANA INDS',         
'SURANA TELE.',        
'SURAT TEXT.',         
'SURYA PHARMA',        
'SURYA ROSHNI',        
'SURYACHAKRA',         
'SURYADEEP SA',        
'SURYAJYOTI S',        
'SURYANAGRI F',        
'SURYAVA SPIN',        
'SURYLAK.COTT',        
'SUTLEJ TEXT',         
'SUVEN LIFE S',        
'SUZLONENERGY',        
'SV GEMS CORP',        
'SVAM SOFTWAR',        
'SVC SUPERCHE',        
'SWAN MILLS',          
'SWARAJ ENGIN',        
'SWARAJ MAZDA',        
'SWASTI VINAY',        
'SWASTIK INV',         
'SWASTIK SAFE',        
'SWISS GLASS',         
'SWITCH.TECH.',        
'SYBLY INDS.',         
'SYLPH TECH',          
'SYMPHONY COM',        
'SYNCOM FORM.',        
'SYNDICATE BN',        
'SYNERG LOGIN',        
'SYSCHEM (I)',         
'SYSTAMATIX C',        
'T & I GLOBAL',        
'T C M LTD.',          
'T. SPIRITUAL',        
'T.P.L.',              
'TAI INDUST.',         
'TAINWALA CH.',        
'TAJ GVK HOTL',        
'TAK MACHINE.',        
'TAKE SOLUT',          
'TALBROS AUTO',        
'TAMIL.NEWSPR',        
'TAMIL.TELE.',         
'TANEJA AERO.',        
'TANFAC IND.',         
'TANLA',               
'TANTIA CONS',         
'TANU HEALTH.',        
'TAPARIA TOOL',        
'TARAI FOODS',         
'TASTY BITE',          
'TATA CHEM.',          
'TATA COFFEE',         
'TATA COMM',           
'TATA ELXSI',          
'TATA INVEST.',        
'TATA METALIK',        
'TATA MOTORS',         
'TATA POWER',          
'TATA SPONGE',         
'TATA STEEL',          
'TATA STL',            
'TATA TEA',            
'TATA TELESER',        
'TATA YODOGAW',        
'TATACOFNCD',          
'TATASTLCCPS',         
'TATIA GLOB',          
'TCFC FINANCE',        
'TCI FINANCE',         
'TCI INDUS.',          
'TCS LTD.',            
'TECH MAH',            
'TECHNO ELEC',         
'TECHNO FORGE',        
'TECHNOCRAFT',         
'TECHTRN.POLY',        
'TEESTA AGRO',         
'TELE DATA IN',        
'TELEPHOTO EN',        
'TEMPT.FOODS',         
'TERAI TEA CO',        
'TERASOFT(PS',         
'TEXMACO LTD.',        
'TEXPLAST IND',        
'TEZPORE TEA',         
'THACKER',             
'THAKKERS DEV',        
'THAMBI MOD.',         
'THANA ELECT',         
'THEMIS MEDIC',        
'THERMAX',             
'THIRU A.SUG.',        
'THIRUMALAI',          
'THOMAS COOK',         
'TIDE WATE(PS',        
'TIL LTD.',            
'TILAKNAG IND',        
'TIME TECHNO',         
'TIMES GUARAN',        
'TIMEX GROUP',         
'TIMKEN (I)',          
'TINPLATE',            
'TIPS INDUS.',         
'TIRUP FOAM',          
'TIRUPATI IND',        
'TIRUPATI STA',        
'TITAGARH IND',        
'TITAGARH WAG',        
'TITAN BIOTEC',        
'TITAN IND.',          
'TITAN SECUR.',        
'TITAN12MAY6',         
'TITANOR C(PS',        
'TODAYS WRITI',        
'TOKYO FINANC',        
'TOKYO PLAST',         
'TONIRA PHARM',        
'TORNT POWER',         
'TORR.GJ.BIO',         
'TORRENT CABL',        
'TORRENT PHAR',        
'TOURISM FINA',        
'TOYAMA ELECT',        
'TPL PLAST',           
'TRADE WINGS',         
'TRANS ASIAC',         
'TRANSCHEM',           
'TRANSCON RES',        
'TRANSCORP IN',        
'TRANSFREIGHT',        
'TRANSGENE BI',        
'TRANSPEK FIN',        
'TRANSPEK',            
'TRANSPORT CO',        
'TRANSWARRANT',        
'TRC FINAN.SE',        
'TREND ELECT',         
'TRENT LTD.',          
'TRENT07JUL10',        
'TRENTWAR7JUL',        
'TRF LTD.',            
'TRIBHUVAN HS',        
'TRICOM INDIA',        
'TRIGYN TECH',         
'TRIJAL IND.',         
'TRIL',                
'TRIPEX OVERS',        
'TRISHAKTI EL',        
'TRITON CORP.',        
'TRITON VALVE',        
'TRIUMPH INT.',        
'TRIVENI ENGG',        
'TRIVENI GLAS',        
'TT LTD.',             
'TTK HEALTHCA',        
'TTK PRESTIGE',        
'TUBE INV.',           
'TUDOR INDIA',         
'TULIP STAR H',        
'TULIP TELE',          
'TULSI EXTRU',         
'TULSYAN NEC',         
'TUTICORIN.',          
'TUTIS TECH',          
'TV 18 IN(FII',        
'TV 18 INDIA',         
'TVS MOTOR L',         
'TVS SRICHAKR',        
'TVSELE',              
'TVTN',                
'TWE.FIR.CENT',        
'TWILITAKA PH',        
'TWINSTAR SOF',        
'TYCHE INDS',          
'TYCHE PERIPH',        
'TYROON TEA',          
'U G HOTELS',          
'U.P.HOTELS',          
'UB ENGG.',            
'UCAL FUEL',           
'UCOBANK',             
'UFLEX LTD',           
'UGAR SUGAR',          
'ULTRAMARINE',         
'ULTRATECH CM',        
'UMA PETROPRO',        
'UMANG DAIR',          
'UNI ABEX',            
'UNI OFF AUTO',        
'UNI ROYAL IN',        
'UNICHEM LAB',         
'UNIFLEX CABL',        
'UNIMER INDIA',        
'UNIMIN INDIA',        
'UNION BANK L',        
'UNIONBANKSL',         
'UNIPHOS ENT.',        
'UNIPLY IND',          
'UNIPRODUCTS',         
'UNIROYAL MAR',        
'UNITD SPR',           
'UNITECH LTD',         
'UNITED BREWA',        
'UNITED BREWE',        
'UNITED CRED.',        
'UNITED DRILL',        
'UNITED PHOSH',        
'UNITED TEXT.',        
'UNITEX DES',          
'UNITY INFRA',         
'UNIV.CABLE',          
'UNIV.PRIME',          
'UNIV.STARCH',         
'UNIVERSAL A',         
'UNJHA FORMUL',        
'UPPER GANGES',        
'UPSURGE INV.',        
'USHA INTE(PS',        
'USHA MART.IN',        
'USHA MART.LT',        
'USHAKIRAN FI',        
'USHDEV INTNL',        
'USHER AGRO',          
'UT LTD.',             
'UTTAM GALVA',         
'UTTAM SUGAR',         
'UTV SOFTWARE',        
'UV DER HORST',        
'V GUARD IND',         
'V.B.DESAI',           
'VADILAL ENT',         
'VADILAL IND',         
'VAIBHAV GEMS',        
'VAKRANGEE SO',        
'VALECHA ENGG',        
'VALIANT COMM',        
'VALLABH STEL',        
'VALLEY INDIA',        
'VALSON INDUS',        
'VALUE IND L',         
'VALUEMART',           
'VAMA INDS',           
'VAMSHI RUBB.',        
'VANASTH.TEXT',        
'VAPI PAPER',          
'VARD HOLDNG',         
'VARDH TEXT',          
'VARDHMAN IND',        
'VARDHMAN LAB',        
'VARDHMAN POL',        
'VARUN INDS',          
'VARUN SHIP.',         
'VAS INFRA',           
'VBC FERRO',           
'VBC FINANCE',         
'VBC IND.',            
'VCK CAPITAL',         
'VEDANT HOTEL',        
'VEEJAY LAKSH',        
'VEER ENERGY',         
'VELAN HOTELS',        
'VENKAT PHARM',        
'VENKEY'S (I)',        
'VENLON ENTR',         
'VENTURA TEXL',        
'VENUS REMEDI',        
'VENUS SUGAR',         
'VENUS UNIVER',        
'VERTEX SEC.',         
'VERTEX SPG',          
'VESUVIUS IND',        
'VICEROY HOTE',        
'VICTORIA MIL',        
'VICTORY PAPR',        
'VICTORY PROJ',        
'VIDEOCON IND',        
'VIDHI DYESTU',        
'VIJAY SHA.BU',        
'VIJAY TEXTIL',        
'VIJAYA BANK',         
'VIJAYES TEXT',        
'VIKAS PROFN',         
'VIKAS WSP',           
'VIKASH METAL',        
'VIKRAM THERM',        
'VIMAL OIL FD',        
'VIMTA LABS',          
'VINATI ORG.',         
'VINAY CEMENT',        
'VINDHYA TELE',        
'VINTAGE SECU',        
'VINTRON INF.',        
'VINYL CHEM',          
'VINYOFLEX LT',        
'VIP INDUS.',          
'VIPPY INDUS.',        
'VIPPY SPIN.',         
'VIPUL DYE CH',        
'VIPUL LTD',           
'VIRAT CRANE',         
'VIRAT INDUS.',        
'VIRINCHI CON',        
'VIRTUALSOFT.',        
'VISA STEEL',          
'VISAKA IND.',         
'VISESH INFO.',        
'VISHAL MALLE',        
'VISHAL RETAI',        
'VISHALEXPO',          
'VISHNU CHEM',         
'VISION CORPO',        
'VISISTH MERC',        
'VISISTH TRAD',        
'VISTA PHARMA',        
'VISU INTL',           
'VITAL COMM.',         
'VIVIMED LABS',        
'VLS FINANCE',         
'VMF SOFTEC',          
'VOGUE TEXTIL',        
'VOITH PAPER',         
'VOLTAMP TRAN',        
'VOLTAS LTD',          
'VORA CONST.',         
'VST INDUS.',          
'VST TILLERS',         
'VTM LTD',             
'VULCAN ENG.',         
'VXL INSTRUM.',        
'VYAPAR INDS',         
'VYBRA AUTO.',         
'W.H.BRADY',           
'W.S.INDUSTR.',        
'WADALA COMM',         
'WALCHAND PF',         
'WALCHANDNGR',         
'WALL ST.FIN.',        
'WALLFORT FIN',        
'WANBURY LTD',         
'WARNER MULTI',        
'WARREN TEA',          
'WATERBASE',           
'WEAROLOGY LT',        
'WEBEL-SL ENY',        
'WEIZMANN FIN',        
'WEIZMANN LTD',        
'WELCAST',             
'WELCURE DRUG',        
'WELL PACK PA',        
'WELLWORTH OV',        
'WELSP GUJ SR',        
'WELSPUN (I)',         
'WELSPUN SYNT',        
'WENDT(INDIA)',        
'WEST COAST',          
'WEST.(I)SHIP',        
'WHEELS INDIA',        
'WHIRLPOOL',           
'WHITE DIAMON',        
'WHITE LION A',        
'WILLARD IND',         
'WILLIAM.FIN.',        
'WILLIAM.MAGO',        
'WIM PLAST LT',        
'WIMSOME TEXT',        
'WINDSOR MACH',        
'WINRO COMMR.',        
'WINSOME BREW',        
'WINSOME YARN',        
'WINTAC LTD',          
'WIPRO LTD.',          
'WIRE& WIRLES',        
'WIRES FABRIK',        
'WISEC GLOBAL',        
'WOCKHARDT',           
'WOMEN NETWOR',        
'WOOLITE MERC',        
'WORLDWIDE LE',        
'WPIL LTD.',           
'WYETH LTD.',          
'XL TEL ENE',          
'XO INFOTECH',         
'XPRO INDI(PS',        
'YARN SYNDICA',        
'YASH MANAGE.',        
'YASH PAPERS',         
'YASHRAJ SEC.',        
'YASRAJ CONT.',        
'YENKEY DRUGS',        
'YES BANK',            
'YOGI SUNGWON',        
'YUKEN INDIA',         
'ZANDU PHARM',         
'ZEE ENTER',           
'ZEE NEWS',            
'ZEN TECH',            
'ZENITH BIRLA',        
'ZENITH COMP.',        
'ZENITH EXP.',         
'ZENITH FIBRE',        
'ZENITH HEALT',        
'ZENITH INFO.',        
'ZENOTECH',            
'ZENSAR TECH.',        
'ZENU INFOTEC',        
'ZF STEERING',         
'ZICOM ELECTR',        
'ZIGMA SOFT.',         
'ZODIAC CLOTH',        
'ZODIAC JRD',          
'ZUARI FOREX',         
'ZUARI INDUS.',        
'ZYDEN GENTEC',        
'ZYLOG ////System'
];